/*
 * Generated file (for kernel version 5.14.0-rc7-mm1+ on x86_64). Do not edit manually or check in VCS.
 *
 */
#ifndef SYSCALLENTS_H
#define SYSCALLENTS_H

#include "trace/internal/syscall_types.h"

#define TOTAL_NUM_SYSCALLS      397
#define MAX_SYSCALL_NUM         548
#define SYSCALLS_ARR_SIZE       (MAX_SYSCALL_NUM + 1)


/* -- Array index consts (see also header `<arch>-linux-gnu/asm/unistd_64.h`, e.g., for amd64 `/usr/include/x86_64-linux-gnu/asm/unistd_64.h`) -- */
#define __SNR_read                     0
#define __SNR_write                    1
#define __SNR_open                     2
#define __SNR_close                    3
#define __SNR_stat                     4
#define __SNR_fstat                    5
#define __SNR_lstat                    6
#define __SNR_poll                     7
#define __SNR_lseek                    8
#define __SNR_mmap                     9
#define __SNR_mprotect                 10
#define __SNR_munmap                   11
#define __SNR_brk                      12
#define __SNR_rt_sigaction             13
#define __SNR_rt_sigprocmask           14
#define __SNR_rt_sigreturn             15
#define __SNR_ioctl                    16
#define __SNR_pread64                  17
#define __SNR_pwrite64                 18
#define __SNR_readv                    19
#define __SNR_writev                   20
#define __SNR_access                   21
#define __SNR_pipe                     22
#define __SNR_select                   23
#define __SNR_sched_yield              24
#define __SNR_mremap                   25
#define __SNR_msync                    26
#define __SNR_mincore                  27
#define __SNR_madvise                  28
#define __SNR_shmget                   29
#define __SNR_shmat                    30
#define __SNR_shmctl                   31
#define __SNR_dup                      32
#define __SNR_dup2                     33
#define __SNR_pause                    34
#define __SNR_nanosleep                35
#define __SNR_getitimer                36
#define __SNR_alarm                    37
#define __SNR_setitimer                38
#define __SNR_getpid                   39
#define __SNR_sendfile                 40
#define __SNR_socket                   41
#define __SNR_connect                  42
#define __SNR_accept                   43
#define __SNR_sendto                   44
#define __SNR_recvfrom                 45
#define __SNR_sendmsg                  46
#define __SNR_recvmsg                  47
#define __SNR_shutdown                 48
#define __SNR_bind                     49
#define __SNR_listen                   50
#define __SNR_getsockname              51
#define __SNR_getpeername              52
#define __SNR_socketpair               53
#define __SNR_setsockopt               54
#define __SNR_getsockopt               55
#define __SNR_clone                    56
#define __SNR_fork                     57
#define __SNR_vfork                    58
#define __SNR_execve                   59
#define __SNR_exit                     60
#define __SNR_wait4                    61
#define __SNR_kill                     62
#define __SNR_uname                    63
#define __SNR_semget                   64
#define __SNR_semop                    65
#define __SNR_semctl                   66
#define __SNR_shmdt                    67
#define __SNR_msgget                   68
#define __SNR_msgsnd                   69
#define __SNR_msgrcv                   70
#define __SNR_msgctl                   71
#define __SNR_fcntl                    72
#define __SNR_flock                    73
#define __SNR_fsync                    74
#define __SNR_fdatasync                75
#define __SNR_truncate                 76
#define __SNR_ftruncate                77
#define __SNR_getdents                 78
#define __SNR_getcwd                   79
#define __SNR_chdir                    80
#define __SNR_fchdir                   81
#define __SNR_rename                   82
#define __SNR_mkdir                    83
#define __SNR_rmdir                    84
#define __SNR_creat                    85
#define __SNR_link                     86
#define __SNR_unlink                   87
#define __SNR_symlink                  88
#define __SNR_readlink                 89
#define __SNR_chmod                    90
#define __SNR_fchmod                   91
#define __SNR_chown                    92
#define __SNR_fchown                   93
#define __SNR_lchown                   94
#define __SNR_umask                    95
#define __SNR_gettimeofday             96
#define __SNR_getrlimit                97
#define __SNR_getrusage                98
#define __SNR_sysinfo                  99
#define __SNR_times                    100
#define __SNR_ptrace                   101
#define __SNR_getuid                   102
#define __SNR_syslog                   103
#define __SNR_getgid                   104
#define __SNR_setuid                   105
#define __SNR_setgid                   106
#define __SNR_geteuid                  107
#define __SNR_getegid                  108
#define __SNR_setpgid                  109
#define __SNR_getppid                  110
#define __SNR_getpgrp                  111
#define __SNR_setsid                   112
#define __SNR_setreuid                 113
#define __SNR_setregid                 114
#define __SNR_getgroups                115
#define __SNR_setgroups                116
#define __SNR_setresuid                117
#define __SNR_getresuid                118
#define __SNR_setresgid                119
#define __SNR_getresgid                120
#define __SNR_getpgid                  121
#define __SNR_setfsuid                 122
#define __SNR_setfsgid                 123
#define __SNR_getsid                   124
#define __SNR_capget                   125
#define __SNR_capset                   126
#define __SNR_rt_sigpending            127
#define __SNR_rt_sigtimedwait          128
#define __SNR_rt_sigqueueinfo          129
#define __SNR_rt_sigsuspend            130
#define __SNR_sigaltstack              131
#define __SNR_utime                    132
#define __SNR_mknod                    133
#define __SNR_uselib                   134
#define __SNR_personality              135
#define __SNR_ustat                    136
#define __SNR_statfs                   137
#define __SNR_fstatfs                  138
#define __SNR_sysfs                    139
#define __SNR_getpriority              140
#define __SNR_setpriority              141
#define __SNR_sched_setparam           142
#define __SNR_sched_getparam           143
#define __SNR_sched_setscheduler       144
#define __SNR_sched_getscheduler       145
#define __SNR_sched_get_priority_max   146
#define __SNR_sched_get_priority_min   147
#define __SNR_sched_rr_get_interval    148
#define __SNR_mlock                    149
#define __SNR_munlock                  150
#define __SNR_mlockall                 151
#define __SNR_munlockall               152
#define __SNR_vhangup                  153
#define __SNR_modify_ldt               154
#define __SNR_pivot_root               155
#define __SNR__sysctl                  156
#define __SNR_prctl                    157
#define __SNR_arch_prctl               158
#define __SNR_adjtimex                 159
#define __SNR_setrlimit                160
#define __SNR_chroot                   161
#define __SNR_sync                     162
#define __SNR_acct                     163
#define __SNR_settimeofday             164
#define __SNR_mount                    165
#define __SNR_umount2                  166
#define __SNR_swapon                   167
#define __SNR_swapoff                  168
#define __SNR_reboot                   169
#define __SNR_sethostname              170
#define __SNR_setdomainname            171
#define __SNR_iopl                     172
#define __SNR_ioperm                   173
#define __SNR_create_module            174
#define __SNR_init_module              175
#define __SNR_delete_module            176
#define __SNR_get_kernel_syms          177
#define __SNR_query_module             178
#define __SNR_quotactl                 179
#define __SNR_nfsservctl               180
#define __SNR_getpmsg                  181
#define __SNR_putpmsg                  182
#define __SNR_afs_syscall              183
#define __SNR_tuxcall                  184
#define __SNR_security                 185
#define __SNR_gettid                   186
#define __SNR_readahead                187
#define __SNR_setxattr                 188
#define __SNR_lsetxattr                189
#define __SNR_fsetxattr                190
#define __SNR_getxattr                 191
#define __SNR_lgetxattr                192
#define __SNR_fgetxattr                193
#define __SNR_listxattr                194
#define __SNR_llistxattr               195
#define __SNR_flistxattr               196
#define __SNR_removexattr              197
#define __SNR_lremovexattr             198
#define __SNR_fremovexattr             199
#define __SNR_tkill                    200
#define __SNR_time                     201
#define __SNR_futex                    202
#define __SNR_sched_setaffinity        203
#define __SNR_sched_getaffinity        204
#define __SNR_set_thread_area          205
#define __SNR_io_setup                 206
#define __SNR_io_destroy               207
#define __SNR_io_getevents             208
#define __SNR_io_submit                209
#define __SNR_io_cancel                210
#define __SNR_get_thread_area          211
#define __SNR_lookup_dcookie           212
#define __SNR_epoll_create             213
#define __SNR_epoll_ctl_old            214
#define __SNR_epoll_wait_old           215
#define __SNR_remap_file_pages         216
#define __SNR_getdents64               217
#define __SNR_set_tid_address          218
#define __SNR_restart_syscall          219
#define __SNR_semtimedop               220
#define __SNR_fadvise64                221
#define __SNR_timer_create             222
#define __SNR_timer_settime            223
#define __SNR_timer_gettime            224
#define __SNR_timer_getoverrun         225
#define __SNR_timer_delete             226
#define __SNR_clock_settime            227
#define __SNR_clock_gettime            228
#define __SNR_clock_getres             229
#define __SNR_clock_nanosleep          230
#define __SNR_exit_group               231
#define __SNR_epoll_wait               232
#define __SNR_epoll_ctl                233
#define __SNR_tgkill                   234
#define __SNR_utimes                   235
#define __SNR_vserver                  236
#define __SNR_mbind                    237
#define __SNR_set_mempolicy            238
#define __SNR_get_mempolicy            239
#define __SNR_mq_open                  240
#define __SNR_mq_unlink                241
#define __SNR_mq_timedsend             242
#define __SNR_mq_timedreceive          243
#define __SNR_mq_notify                244
#define __SNR_mq_getsetattr            245
#define __SNR_kexec_load               246
#define __SNR_waitid                   247
#define __SNR_add_key                  248
#define __SNR_request_key              249
#define __SNR_keyctl                   250
#define __SNR_ioprio_set               251
#define __SNR_ioprio_get               252
#define __SNR_inotify_init             253
#define __SNR_inotify_add_watch        254
#define __SNR_inotify_rm_watch         255
#define __SNR_migrate_pages            256
#define __SNR_openat                   257
#define __SNR_mkdirat                  258
#define __SNR_mknodat                  259
#define __SNR_fchownat                 260
#define __SNR_futimesat                261
#define __SNR_newfstatat               262
#define __SNR_unlinkat                 263
#define __SNR_renameat                 264
#define __SNR_linkat                   265
#define __SNR_symlinkat                266
#define __SNR_readlinkat               267
#define __SNR_fchmodat                 268
#define __SNR_faccessat                269
#define __SNR_pselect6                 270
#define __SNR_ppoll                    271
#define __SNR_unshare                  272
#define __SNR_set_robust_list          273
#define __SNR_get_robust_list          274
#define __SNR_splice                   275
#define __SNR_tee                      276
#define __SNR_sync_file_range          277
#define __SNR_vmsplice                 278
#define __SNR_move_pages               279
#define __SNR_utimensat                280
#define __SNR_epoll_pwait              281
#define __SNR_signalfd                 282
#define __SNR_timerfd_create           283
#define __SNR_eventfd                  284
#define __SNR_fallocate                285
#define __SNR_timerfd_settime          286
#define __SNR_timerfd_gettime          287
#define __SNR_accept4                  288
#define __SNR_signalfd4                289
#define __SNR_eventfd2                 290
#define __SNR_epoll_create1            291
#define __SNR_dup3                     292
#define __SNR_pipe2                    293
#define __SNR_inotify_init1            294
#define __SNR_preadv                   295
#define __SNR_pwritev                  296
#define __SNR_rt_tgsigqueueinfo        297
#define __SNR_perf_event_open          298
#define __SNR_recvmmsg                 299
#define __SNR_fanotify_init            300
#define __SNR_fanotify_mark            301
#define __SNR_prlimit64                302
#define __SNR_name_to_handle_at        303
#define __SNR_open_by_handle_at        304
#define __SNR_clock_adjtime            305
#define __SNR_syncfs                   306
#define __SNR_sendmmsg                 307
#define __SNR_setns                    308
#define __SNR_getcpu                   309
#define __SNR_process_vm_readv         310
#define __SNR_process_vm_writev        311
#define __SNR_kcmp                     312
#define __SNR_finit_module             313
#define __SNR_sched_setattr            314
#define __SNR_sched_getattr            315
#define __SNR_renameat2                316
#define __SNR_seccomp                  317
#define __SNR_getrandom                318
#define __SNR_memfd_create             319
#define __SNR_kexec_file_load          320
#define __SNR_bpf                      321
#define __SNR_execveat                 322
#define __SNR_userfaultfd              323
#define __SNR_membarrier               324
#define __SNR_mlock2                   325
#define __SNR_copy_file_range          326
#define __SNR_preadv2                  327
#define __SNR_pwritev2                 328
#define __SNR_pkey_mprotect            329
#define __SNR_pkey_alloc               330
#define __SNR_pkey_free                331
#define __SNR_statx                    332
#define __SNR_io_pgetevents            333
#define __SNR_rseq                     334
#define __SNR_pidfd_send_signal        424
#define __SNR_io_uring_setup           425
#define __SNR_io_uring_enter           426
#define __SNR_io_uring_register        427
#define __SNR_open_tree                428
#define __SNR_move_mount               429
#define __SNR_fsopen                   430
#define __SNR_fsconfig                 431
#define __SNR_fsmount                  432
#define __SNR_fspick                   433
#define __SNR_pidfd_open               434
#define __SNR_clone3                   435
#define __SNR_close_range              436
#define __SNR_openat2                  437
#define __SNR_pidfd_getfd              438
#define __SNR_faccessat2               439
#define __SNR_process_madvise          440
#define __SNR_epoll_pwait2             441
#define __SNR_mount_setattr            442
#define __SNR_quotactl_fd              443
#define __SNR_landlock_create_ruleset  444
#define __SNR_landlock_add_rule        445
#define __SNR_landlock_restrict_self   446
#define __SNR_memfd_secret             447
#define __SNR_process_mrelease         448
#define __SNR_COMPAT_rt_sigaction      512
#define __SNR_COMPAT_rt_sigreturn      513
#define __SNR_COMPAT_ioctl             514
#define __SNR_COMPAT_readv             515
#define __SNR_COMPAT_writev            516
#define __SNR_COMPAT_recvfrom          517
#define __SNR_COMPAT_sendmsg           518
#define __SNR_COMPAT_recvmsg           519
#define __SNR_COMPAT_execve            520
#define __SNR_COMPAT_ptrace            521
#define __SNR_COMPAT_rt_sigpending     522
#define __SNR_COMPAT_rt_sigtimedwait   523
#define __SNR_COMPAT_rt_sigqueueinfo   524
#define __SNR_COMPAT_sigaltstack       525
#define __SNR_COMPAT_timer_create      526
#define __SNR_COMPAT_mq_notify         527
#define __SNR_COMPAT_kexec_load        528
#define __SNR_COMPAT_waitid            529
#define __SNR_COMPAT_set_robust_list   530
#define __SNR_COMPAT_get_robust_list   531
#define __SNR_COMPAT_vmsplice          532
#define __SNR_COMPAT_move_pages        533
#define __SNR_COMPAT_preadv            534
#define __SNR_COMPAT_pwritev           535
#define __SNR_COMPAT_rt_tgsigqueueinfo 536
#define __SNR_COMPAT_recvmmsg          537
#define __SNR_COMPAT_sendmmsg          538
#define __SNR_COMPAT_process_vm_readv  539
#define __SNR_COMPAT_process_vm_writev 540
#define __SNR_COMPAT_setsockopt        541
#define __SNR_COMPAT_getsockopt        542
#define __SNR_COMPAT_io_setup          543
#define __SNR_COMPAT_io_submit         544
#define __SNR_COMPAT_execveat          545
#define __SNR_COMPAT_preadv2           546
#define __SNR_COMPAT_pwritev2          547
#define __SNR_inform                   548


extern const syscall_entry_t syscalls[];


#endif /* SYSCALLENTS_H */
