<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0x387): unsigned char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xf8f): short unsigned int
<1><2b>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x8cc): unsigned int
<1><32>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x2b>
<1><37>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x6c3): long unsigned int
<1><3e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x338): signed char
<1><45>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x24e): __uint8_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_decl_column : 23
DW_AT_type        : <0x1d>
<1><51>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0xda6): short int
<1><58>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x459): __uint16_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 39
DW_AT_decl_column : 28
DW_AT_type        : <0x24>
<1><64>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><6b>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x64>
<1><70>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x7d2): __uint32_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 41
DW_AT_decl_column : 22
DW_AT_type        : <0x2b>
<1><7c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x802): long long int
<1><83>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x6a9): __uint64_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 47
DW_AT_decl_column : 46
DW_AT_type        : <0x8f>
<1><8f>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xaad): long long unsigned int
<1><96>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x717): __quad_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 55
DW_AT_decl_column : 37
DW_AT_type        : <0x7c>
<1><a2>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xae3): __off_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 140
DW_AT_decl_column : 25
DW_AT_type        : <0xae>
<1><ae>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x2b4): long int
<1><b5>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xcae): __off64_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 141
DW_AT_decl_column : 27
DW_AT_type        : <0x96>
<1><c1>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xc05): __time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 148
DW_AT_decl_column : 26
DW_AT_type        : <0xae>
<1><cd>
Abbrev Number: 6 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
<1><cf>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xcd>
<1><d4>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x3c5): __syscall_slong_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 184
DW_AT_decl_column : 33
DW_AT_type        : <0xae>
<1><e0>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xe6>
<1><e6>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x41f): char
<1><ed>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xe6>
<1><f2>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x344): uint8_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 24
DW_AT_decl_column : 19
DW_AT_type        : <0x45>
<1><fe>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xace): uint16_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 25
DW_AT_decl_column : 20
DW_AT_type        : <0x58>
<1><10a>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xf35): uint32_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_decl_column : 20
DW_AT_type        : <0x70>
<1><116>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xdb6): uint64_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 27
DW_AT_decl_column : 20
DW_AT_type        : <0x83>
<1><122>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x39): size_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 209
DW_AT_decl_column : 23
DW_AT_type        : <0x2b>
<1><12e>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x122>
<1><133>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xa56): timespec
DW_AT_byte_size   : 8
DW_AT_decl_file   : 4
DW_AT_decl_line   : 9
DW_AT_decl_column : 8
DW_AT_sibling     : <0x15f>
<2><140>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x105c): tv_sec
DW_AT_decl_file   : 4
DW_AT_decl_line   : 11
DW_AT_decl_column : 12
DW_AT_type        : <0xc1>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><14f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xddc): tv_nsec
DW_AT_decl_file   : 4
DW_AT_decl_line   : 12
DW_AT_decl_column : 21
DW_AT_type        : <0xd4>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><15f>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 12
DW_AT_encoding    : 4	(float)
DW_AT_name        : (indirect string, offset: 0xa18): long double
<1><166>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 16
DW_AT_encoding    : 4	(float)
DW_AT_name        : (indirect string, offset: 0xf5e): _Float128
<1><16d>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x26b): __environ
DW_AT_decl_file   : 5
DW_AT_decl_line   : 546
DW_AT_decl_column : 15
DW_AT_type        : <0x17c>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><17c>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xe0>
<1><182>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x37f): environ
DW_AT_decl_file   : 5
DW_AT_decl_line   : 548
DW_AT_decl_column : 15
DW_AT_type        : <0x17c>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><191>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf79): optarg
DW_AT_decl_file   : 6
DW_AT_decl_line   : 36
DW_AT_decl_column : 14
DW_AT_type        : <0xe0>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><19f>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x67c): optind
DW_AT_decl_file   : 6
DW_AT_decl_line   : 50
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1ad>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xbf4): opterr
DW_AT_decl_file   : 6
DW_AT_decl_line   : 55
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1bb>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xa93): optopt
DW_AT_decl_file   : 6
DW_AT_decl_line   : 59
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1c9>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xed>
<1><1cf>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1c9>
<1><1d4>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1da>
<1><1da>
Abbrev Number: 12 (DW_TAG_const_type)
<1><1db>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x34c): _IO_FILE
DW_AT_byte_size   : 148
DW_AT_decl_file   : 7
DW_AT_decl_line   : 245
DW_AT_decl_column : 8
DW_AT_sibling     : <0x3b3>
<2><1e8>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x973): _flags
DW_AT_decl_file   : 7
DW_AT_decl_line   : 246
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1f7>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4af): _IO_read_ptr
DW_AT_decl_file   : 7
DW_AT_decl_line   : 251
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><206>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xee7): _IO_read_end
DW_AT_decl_file   : 7
DW_AT_decl_line   : 252
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><215>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6f4): _IO_read_base
DW_AT_decl_file   : 7
DW_AT_decl_line   : 253
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><224>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x132): _IO_write_base
DW_AT_decl_file   : 7
DW_AT_decl_line   : 254
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><233>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfc8): _IO_write_ptr
DW_AT_decl_file   : 7
DW_AT_decl_line   : 255
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><242>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x844): _IO_write_end
DW_AT_decl_file   : 7
DW_AT_decl_line   : 256
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><252>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8b5): _IO_buf_base
DW_AT_decl_file   : 7
DW_AT_decl_line   : 257
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><262>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd51): _IO_buf_end
DW_AT_decl_file   : 7
DW_AT_decl_line   : 258
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><272>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1c3): _IO_save_base
DW_AT_decl_file   : 7
DW_AT_decl_line   : 260
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><282>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc69): _IO_backup_base
DW_AT_decl_file   : 7
DW_AT_decl_line   : 261
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><292>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xba): _IO_save_end
DW_AT_decl_file   : 7
DW_AT_decl_line   : 262
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><2a2>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x53a): _markers
DW_AT_decl_file   : 7
DW_AT_decl_line   : 264
DW_AT_decl_column : 22
DW_AT_type        : <0x402>
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><2b2>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x206): _chain
DW_AT_decl_file   : 7
DW_AT_decl_line   : 266
DW_AT_decl_column : 20
DW_AT_type        : <0x408>
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><2c2>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf49): _fileno
DW_AT_decl_file   : 7
DW_AT_decl_line   : 268
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><2d2>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6e0): _flags2
DW_AT_decl_file   : 7
DW_AT_decl_line   : 272
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><2e2>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x77e): _old_offset
DW_AT_decl_file   : 7
DW_AT_decl_line   : 274
DW_AT_decl_column : 13
DW_AT_type        : <0xa2>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><2f2>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x239): _cur_column
DW_AT_decl_file   : 7
DW_AT_decl_line   : 278
DW_AT_decl_column : 18
DW_AT_type        : <0x24>
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><302>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe08): _vtable_offset
DW_AT_decl_file   : 7
DW_AT_decl_line   : 279
DW_AT_decl_column : 15
DW_AT_type        : <0x3e>
DW_AT_data_member_location: 2 byte block: 23 46 	(DW_OP_plus_uconst: 70)
<2><312>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc79): _shortbuf
DW_AT_decl_file   : 7
DW_AT_decl_line   : 280
DW_AT_decl_column : 8
DW_AT_type        : <0x40e>
DW_AT_data_member_location: 2 byte block: 23 47 	(DW_OP_plus_uconst: 71)
<2><322>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x173): _lock
DW_AT_decl_file   : 7
DW_AT_decl_line   : 284
DW_AT_decl_column : 15
DW_AT_type        : <0x41e>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><332>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x60d): _offset
DW_AT_decl_file   : 7
DW_AT_decl_line   : 293
DW_AT_decl_column : 15
DW_AT_type        : <0xb5>
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<2><342>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x913): __pad1
DW_AT_decl_file   : 7
DW_AT_decl_line   : 301
DW_AT_decl_column : 9
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 54 	(DW_OP_plus_uconst: 84)
<2><352>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x91a): __pad2
DW_AT_decl_file   : 7
DW_AT_decl_line   : 302
DW_AT_decl_column : 9
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 58 	(DW_OP_plus_uconst: 88)
<2><362>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x921): __pad3
DW_AT_decl_file   : 7
DW_AT_decl_line   : 303
DW_AT_decl_column : 9
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 5c 	(DW_OP_plus_uconst: 92)
<2><372>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x928): __pad4
DW_AT_decl_file   : 7
DW_AT_decl_line   : 304
DW_AT_decl_column : 9
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 60 	(DW_OP_plus_uconst: 96)
<2><382>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x92f): __pad5
DW_AT_decl_file   : 7
DW_AT_decl_line   : 306
DW_AT_decl_column : 10
DW_AT_type        : <0x122>
DW_AT_data_member_location: 2 byte block: 23 64 	(DW_OP_plus_uconst: 100)
<2><392>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x997): _mode
DW_AT_decl_file   : 7
DW_AT_decl_line   : 307
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<2><3a2>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x70e): _unused2
DW_AT_decl_file   : 7
DW_AT_decl_line   : 309
DW_AT_decl_column : 8
DW_AT_type        : <0x424>
DW_AT_data_member_location: 2 byte block: 23 6c 	(DW_OP_plus_uconst: 108)
<1><3b3>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xa38): FILE
DW_AT_decl_file   : 8
DW_AT_decl_line   : 7
DW_AT_decl_column : 25
DW_AT_type        : <0x1db>
<1><3bf>
Abbrev Number: 14 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x44e): _IO_lock_t
DW_AT_decl_file   : 7
DW_AT_decl_line   : 154
DW_AT_decl_column : 14
<1><3c7>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x2f6): _IO_marker
DW_AT_byte_size   : 12
DW_AT_decl_file   : 7
DW_AT_decl_line   : 160
DW_AT_decl_column : 8
DW_AT_sibling     : <0x402>
<2><3d4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xca8): _next
DW_AT_decl_file   : 7
DW_AT_decl_line   : 161
DW_AT_decl_column : 22
DW_AT_type        : <0x402>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><3e3>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x936): _sbuf
DW_AT_decl_file   : 7
DW_AT_decl_line   : 162
DW_AT_decl_column : 20
DW_AT_type        : <0x408>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><3f2>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4ef): _pos
DW_AT_decl_file   : 7
DW_AT_decl_line   : 166
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><402>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x3c7>
<1><408>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1db>
<1><40e>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xe6>
DW_AT_sibling     : <0x41e>
<2><417>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 0
<1><41e>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x3bf>
<1><424>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xe6>
DW_AT_sibling     : <0x434>
<2><42d>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 39
<1><434>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x3f1): _IO_FILE_plus
DW_AT_declaration : 1
<1><43a>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x6b4): _IO_2_1_stdin_
DW_AT_decl_file   : 7
DW_AT_decl_line   : 319
DW_AT_decl_column : 29
DW_AT_type        : <0x434>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><449>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc89): _IO_2_1_stdout_
DW_AT_decl_file   : 7
DW_AT_decl_line   : 320
DW_AT_decl_column : 29
DW_AT_type        : <0x434>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><458>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x89): _IO_2_1_stderr_
DW_AT_decl_file   : 7
DW_AT_decl_line   : 321
DW_AT_decl_column : 29
DW_AT_type        : <0x434>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><467>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x505): stdin
DW_AT_decl_file   : 9
DW_AT_decl_line   : 135
DW_AT_decl_column : 25
DW_AT_type        : <0x408>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><475>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xfa2): stdout
DW_AT_decl_file   : 9
DW_AT_decl_line   : 136
DW_AT_decl_column : 25
DW_AT_type        : <0x408>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><483>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd9f): stderr
DW_AT_decl_file   : 9
DW_AT_decl_line   : 137
DW_AT_decl_column : 25
DW_AT_type        : <0x408>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><491>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x245): sys_nerr
DW_AT_decl_file   : 10
DW_AT_decl_line   : 26
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><49f>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x1cf>
DW_AT_sibling     : <0x4aa>
<2><4a8>
Abbrev Number: 18 (DW_TAG_subrange_type)
<1><4aa>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x49f>
<1><4af>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x514): sys_errlist
DW_AT_decl_file   : 10
DW_AT_decl_line   : 27
DW_AT_decl_column : 26
DW_AT_type        : <0x4aa>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4bd>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x258): _sys_nerr
DW_AT_decl_file   : 10
DW_AT_decl_line   : 30
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4cb>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe17): _sys_errlist
DW_AT_decl_file   : 10
DW_AT_decl_line   : 31
DW_AT_decl_column : 26
DW_AT_type        : <0x4aa>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4d9>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x5e6): program_invocation_name
DW_AT_decl_file   : 11
DW_AT_decl_line   : 45
DW_AT_decl_column : 14
DW_AT_type        : <0xe0>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4e7>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xb0e): program_invocation_short_name
DW_AT_decl_file   : 11
DW_AT_decl_line   : 46
DW_AT_decl_column : 14
DW_AT_type        : <0xe0>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4f5>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xe0>
DW_AT_sibling     : <0x505>
<2><4fe>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 1
<1><505>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1b0): __tzname
DW_AT_decl_file   : 12
DW_AT_decl_line   : 159
DW_AT_decl_column : 14
DW_AT_type        : <0x4f5>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><513>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe83): __daylight
DW_AT_decl_file   : 12
DW_AT_decl_line   : 160
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><521>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x355): __timezone
DW_AT_decl_file   : 12
DW_AT_decl_line   : 161
DW_AT_decl_column : 17
DW_AT_type        : <0xae>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><52f>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x624): tzname
DW_AT_decl_file   : 12
DW_AT_decl_line   : 166
DW_AT_decl_column : 14
DW_AT_type        : <0x4f5>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><53d>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1012): daylight
DW_AT_decl_file   : 12
DW_AT_decl_line   : 174
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><54b>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x49a): timezone
DW_AT_decl_file   : 12
DW_AT_decl_line   : 175
DW_AT_decl_column : 17
DW_AT_type        : <0xae>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><559>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf09): getdate_err
DW_AT_decl_file   : 12
DW_AT_decl_line   : 280
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><568>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x941): debug_flag
DW_AT_decl_file   : 13
DW_AT_decl_line   : 20
DW_AT_decl_column : 13
DW_AT_type        : <0x576>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><576>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x3d7): _Bool
<1><57d>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x576>
<1><582>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x9ee): __kernel_long_t
DW_AT_decl_file   : 14
DW_AT_decl_line   : 15
DW_AT_decl_column : 15
DW_AT_type        : <0xae>
<1><58e>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x4f4): __kernel_ulong_t
DW_AT_decl_file   : 14
DW_AT_decl_line   : 16
DW_AT_decl_column : 23
DW_AT_type        : <0x37>
<1><59a>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x3a3): kernel_long_t
DW_AT_decl_file   : 15
DW_AT_decl_line   : 16
DW_AT_decl_column : 25
DW_AT_type        : <0x582>
<1><5a6>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x7f3): kernel_ulong_t
DW_AT_decl_file   : 15
DW_AT_decl_line   : 17
DW_AT_decl_column : 26
DW_AT_type        : <0x58e>
<1><5b2>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x5a6>
<1><5b7>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xb2c): list_item
DW_AT_byte_size   : 8
DW_AT_decl_file   : 16
DW_AT_decl_line   : 92
DW_AT_decl_column : 8
DW_AT_sibling     : <0x5e3>
<2><5c4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1057): prev
DW_AT_decl_file   : 16
DW_AT_decl_line   : 93
DW_AT_decl_column : 20
DW_AT_type        : <0x5e3>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><5d3>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x104d): next
DW_AT_decl_file   : 16
DW_AT_decl_line   : 94
DW_AT_decl_column : 20
DW_AT_type        : <0x5e3>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><5e3>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x5b7>
<1><5e9>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x7cb): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 17
DW_AT_decl_line   : 11
DW_AT_decl_column : 16
DW_AT_sibling     : <0x642>
<2><5f6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfb9): nargs
DW_AT_decl_file   : 17
DW_AT_decl_line   : 12
DW_AT_decl_column : 11
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><605>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8c2): sys_flags
DW_AT_decl_file   : 17
DW_AT_decl_line   : 13
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><614>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 17
DW_AT_decl_line   : 14
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><623>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x2ed): sys_func
DW_AT_decl_file   : 17
DW_AT_decl_line   : 15
DW_AT_decl_column : 8
DW_AT_type        : <0x64d>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><632>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x262): sys_name
DW_AT_decl_file   : 17
DW_AT_decl_line   : 16
DW_AT_decl_column : 14
DW_AT_type        : <0x1c9>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><642>
Abbrev Number: 20 (DW_TAG_subroutine_type)
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x64d>
<2><64b>
Abbrev Number: 21 (DW_TAG_unspecified_parameters)
<1><64d>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x642>
<1><653>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xe2c): struct_sysent
DW_AT_decl_file   : 17
DW_AT_decl_line   : 17
DW_AT_decl_column : 3
DW_AT_type        : <0x5e9>
<1><65f>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x653>
<1><664>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xcef): current_personality
DW_AT_decl_file   : 18
DW_AT_decl_line   : 158
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><672>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x76d): current_wordsize
DW_AT_decl_file   : 18
DW_AT_decl_line   : 171
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><680>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x9b3): current_klongsize
DW_AT_decl_file   : 18
DW_AT_decl_line   : 176
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><68e>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xc23): ioctlent
DW_AT_byte_size   : 8
DW_AT_decl_file   : 18
DW_AT_decl_line   : 217
DW_AT_decl_column : 16
DW_AT_sibling     : <0x6ba>
<2><69b>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xee0): symbol
DW_AT_decl_file   : 18
DW_AT_decl_line   : 218
DW_AT_decl_column : 14
DW_AT_type        : <0x1c9>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><6aa>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcb8): code
DW_AT_decl_file   : 18
DW_AT_decl_line   : 219
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><6ba>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xbe4): struct_ioctlent
DW_AT_decl_file   : 18
DW_AT_decl_line   : 220
DW_AT_decl_column : 3
DW_AT_type        : <0x68e>
<1><6c6>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x6ba>
<1><6cb>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x761): inject_data
DW_AT_byte_size   : 10
DW_AT_decl_file   : 18
DW_AT_decl_line   : 241
DW_AT_decl_column : 8
DW_AT_sibling     : <0x733>
<2><6d8>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4a9): flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 242
DW_AT_decl_column : 10
DW_AT_type        : <0xf2>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><6e7>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x876): signo
DW_AT_decl_file   : 18
DW_AT_decl_line   : 243
DW_AT_decl_column : 10
DW_AT_type        : <0xf2>
DW_AT_data_member_location: 2 byte block: 23 1 	(DW_OP_plus_uconst: 1)
<2><6f6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x100): rval_idx
DW_AT_decl_file   : 18
DW_AT_decl_line   : 244
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><705>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x40): delay_idx
DW_AT_decl_file   : 18
DW_AT_decl_line   : 245
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><714>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x52c): poke_idx
DW_AT_decl_file   : 18
DW_AT_decl_line   : 246
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<2><723>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x190): scno
DW_AT_decl_file   : 18
DW_AT_decl_line   : 247
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><733>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xe1): inject_opts
DW_AT_byte_size   : 16
DW_AT_decl_file   : 18
DW_AT_decl_line   : 250
DW_AT_decl_column : 8
DW_AT_sibling     : <0x77d>
<2><740>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x991): first
DW_AT_decl_file   : 18
DW_AT_decl_line   : 251
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><74f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1080): last
DW_AT_decl_file   : 18
DW_AT_decl_line   : 252
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><75e>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x37a): step
DW_AT_decl_file   : 18
DW_AT_decl_line   : 253
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><76d>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1052): data
DW_AT_decl_file   : 18
DW_AT_decl_line   : 254
DW_AT_decl_column : 21
DW_AT_type        : <0x6cb>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<1><77d>
Abbrev Number: 22 (DW_TAG_structure_type)
DW_AT_name        : tcb
DW_AT_byte_size   : 196
DW_AT_decl_file   : 18
DW_AT_decl_line   : 262
DW_AT_decl_column : 8
DW_AT_sibling     : <0x9a7>
<2><78b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4a9): flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 263
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><79b>
Abbrev Number: 23 (DW_TAG_member)
DW_AT_name        : pid
DW_AT_decl_file   : 18
DW_AT_decl_line   : 264
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><7ab>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x58): qual_flg
DW_AT_decl_file   : 18
DW_AT_decl_line   : 265
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><7bb>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x36b): currpers
DW_AT_decl_file   : 18
DW_AT_decl_line   : 267
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><7cb>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa8b): u_error
DW_AT_decl_file   : 18
DW_AT_decl_line   : 269
DW_AT_decl_column : 16
DW_AT_type        : <0x37>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><7db>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x190): scno
DW_AT_decl_file   : 18
DW_AT_decl_line   : 270
DW_AT_decl_column : 17
DW_AT_type        : <0x5a6>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><7eb>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xac4): true_scno
DW_AT_decl_file   : 18
DW_AT_decl_line   : 271
DW_AT_decl_column : 17
DW_AT_type        : <0x5a6>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><7fb>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19a): u_arg
DW_AT_decl_file   : 18
DW_AT_decl_line   : 272
DW_AT_decl_column : 17
DW_AT_type        : <0x9a7>
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><80b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8d9): u_rval
DW_AT_decl_file   : 18
DW_AT_decl_line   : 273
DW_AT_decl_column : 16
DW_AT_type        : <0x59a>
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><81b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa0a): sys_func_rval
DW_AT_decl_file   : 18
DW_AT_decl_line   : 274
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><82b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc99): curcol
DW_AT_decl_file   : 18
DW_AT_decl_line   : 275
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><83b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8eb): outf
DW_AT_decl_file   : 18
DW_AT_decl_line   : 276
DW_AT_decl_column : 8
DW_AT_type        : <0x9b7>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><84b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xeb8): staged_output_data
DW_AT_decl_file   : 18
DW_AT_decl_line   : 277
DW_AT_decl_column : 29
DW_AT_type        : <0x9c3>
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><85b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9d5): auxstr
DW_AT_decl_file   : 18
DW_AT_decl_line   : 279
DW_AT_decl_column : 14
DW_AT_type        : <0x1c9>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><86b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x179): _priv_data
DW_AT_decl_file   : 18
DW_AT_decl_line   : 280
DW_AT_decl_column : 8
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<2><87b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xbc7): _free_priv_data
DW_AT_decl_file   : 18
DW_AT_decl_line   : 281
DW_AT_decl_column : 9
DW_AT_type        : <0x9d5>
DW_AT_data_member_location: 2 byte block: 23 50 	(DW_OP_plus_uconst: 80)
<2><88b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x18a): s_ent
DW_AT_decl_file   : 18
DW_AT_decl_line   : 282
DW_AT_decl_column : 23
DW_AT_type        : <0x9db>
DW_AT_data_member_location: 2 byte block: 23 54 	(DW_OP_plus_uconst: 84)
<2><89b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x27): s_prev_ent
DW_AT_decl_file   : 18
DW_AT_decl_line   : 285
DW_AT_decl_column : 23
DW_AT_type        : <0x9db>
DW_AT_data_member_location: 2 byte block: 23 58 	(DW_OP_plus_uconst: 88)
<2><8ab>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x360): inject_vec
DW_AT_decl_file   : 18
DW_AT_decl_line   : 286
DW_AT_decl_column : 22
DW_AT_type        : <0x9e6>
DW_AT_data_member_location: 2 byte block: 23 5c 	(DW_OP_plus_uconst: 92)
<2><8bb>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x720): stime
DW_AT_decl_file   : 18
DW_AT_decl_line   : 287
DW_AT_decl_column : 18
DW_AT_type        : <0x133>
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<2><8cb>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x374): ltime
DW_AT_decl_file   : 18
DW_AT_decl_line   : 288
DW_AT_decl_column : 18
DW_AT_type        : <0x133>
DW_AT_data_member_location: 2 byte block: 23 70 	(DW_OP_plus_uconst: 112)
<2><8db>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf80): atime
DW_AT_decl_file   : 18
DW_AT_decl_line   : 289
DW_AT_decl_column : 18
DW_AT_type        : <0x133>
DW_AT_data_member_location: 2 byte block: 23 78 	(DW_OP_plus_uconst: 120)
<2><8eb>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4a3): etime
DW_AT_decl_file   : 18
DW_AT_decl_line   : 290
DW_AT_decl_column : 18
DW_AT_type        : <0x133>
DW_AT_data_member_location: 3 byte block: 23 80 1 	(DW_OP_plus_uconst: 128)
<2><8fc>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd03): delay_expiration_time
DW_AT_decl_file   : 18
DW_AT_decl_line   : 291
DW_AT_decl_column : 18
DW_AT_type        : <0x133>
DW_AT_data_member_location: 3 byte block: 23 88 1 	(DW_OP_plus_uconst: 136)
<2><90d>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32): pid_ns
DW_AT_decl_file   : 18
DW_AT_decl_line   : 298
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 3 byte block: 23 90 1 	(DW_OP_plus_uconst: 144)
<2><91e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf15): mmap_cache
DW_AT_decl_file   : 18
DW_AT_decl_line   : 304
DW_AT_decl_column : 23
DW_AT_type        : <0xa02>
DW_AT_data_member_location: 3 byte block: 23 94 1 	(DW_OP_plus_uconst: 148)
<2><92f>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa9a): wait_data_idx
DW_AT_decl_file   : 18
DW_AT_decl_line   : 311
DW_AT_decl_column : 9
DW_AT_type        : <0x122>
DW_AT_data_member_location: 3 byte block: 23 98 1 	(DW_OP_plus_uconst: 152)
<2><940>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9dc): delayed_wait_data
DW_AT_decl_file   : 18
DW_AT_decl_line   : 313
DW_AT_decl_column : 24
DW_AT_type        : <0xa0e>
DW_AT_data_member_location: 3 byte block: 23 9c 1 	(DW_OP_plus_uconst: 156)
<2><951>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa4c): wait_list
DW_AT_decl_file   : 18
DW_AT_decl_line   : 314
DW_AT_decl_column : 19
DW_AT_type        : <0x5b7>
DW_AT_data_member_location: 3 byte block: 23 a0 1 	(DW_OP_plus_uconst: 160)
<2><962>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x5fe): vcpu_info_list
DW_AT_decl_file   : 18
DW_AT_decl_line   : 318
DW_AT_decl_column : 20
DW_AT_type        : <0xa1a>
DW_AT_data_member_location: 3 byte block: 23 a8 1 	(DW_OP_plus_uconst: 168)
<2><973>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc5e): unwind_ctx
DW_AT_decl_file   : 18
DW_AT_decl_line   : 322
DW_AT_decl_column : 8
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 3 byte block: 23 ac 1 	(DW_OP_plus_uconst: 172)
<2><984>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x48d): unwind_queue
DW_AT_decl_file   : 18
DW_AT_decl_line   : 323
DW_AT_decl_column : 25
DW_AT_type        : <0xa26>
DW_AT_data_member_location: 3 byte block: 23 b0 1 	(DW_OP_plus_uconst: 176)
<2><995>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x16e): comm
DW_AT_decl_file   : 18
DW_AT_decl_line   : 327
DW_AT_decl_column : 7
DW_AT_type        : <0xa2c>
DW_AT_data_member_location: 3 byte block: 23 b4 1 	(DW_OP_plus_uconst: 180)
<1><9a7>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x5a6>
DW_AT_sibling     : <0x9b7>
<2><9b0>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 5
<1><9b7>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x3b3>
<1><9bd>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xeb8): staged_output_data
DW_AT_declaration : 1
<1><9c3>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x9bd>
<1><9c9>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x9d5>
<2><9cf>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xcd>
<1><9d5>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x9c9>
<1><9db>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x65f>
<1><9e1>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x9db>
<1><9e6>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x9f6>
DW_AT_sibling     : <0x9f6>
<2><9ef>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 2
<1><9f6>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x733>
<1><9fc>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xad): mmap_cache_t
DW_AT_declaration : 1
<1><a02>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x9fc>
<1><a08>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x395): tcb_wait_data
DW_AT_declaration : 1
<1><a0e>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xa08>
<1><a14>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x164): vcpu_info
DW_AT_declaration : 1
<1><a1a>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xa14>
<1><a20>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xe9c): unwind_queue_t
DW_AT_declaration : 1
<1><a26>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xa20>
<1><a2c>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xe6>
DW_AT_sibling     : <0xa3c>
<2><a35>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 15
<1><a3c>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xad7): stub_sysent
DW_AT_decl_file   : 18
DW_AT_decl_line   : 400
DW_AT_decl_column : 28
DW_AT_type        : <0x65f>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><a4b>
Abbrev Number: 26 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x1035): xlat_type
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 19
DW_AT_decl_line   : 13
DW_AT_decl_column : 6
DW_AT_sibling     : <0xa70>
<2><a5d>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x2bd): XT_NORMAL
DW_AT_const_value : 0
<2><a63>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xbfb): XT_SORTED
DW_AT_const_value : 1
<2><a69>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xd86): XT_INDEXED
DW_AT_const_value : 2
<1><a70>
Abbrev Number: 26 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0xb03): xlat_style
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 19
DW_AT_decl_line   : 19
DW_AT_decl_column : 6
DW_AT_sibling     : <0xaad>
<2><a82>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xed): XLAT_STYLE_DEFAULT
DW_AT_const_value : 0
<2><a88>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xb36): XLAT_STYLE_RAW
DW_AT_const_value : 1
<2><a8e>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x1000): XLAT_STYLE_ABBREV
DW_AT_const_value : 2
<2><a94>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x2da): XLAT_STYLE_VERBOSE
DW_AT_const_value : 3
<2><a9a>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x11): XLAT_STYLE_FMT_X
DW_AT_const_value : 0
<2><aa0>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x0): XLAT_STYLE_FMT_U
DW_AT_const_value : 4
<2><aa6>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x106f): XLAT_STYLE_FMT_D
DW_AT_const_value : 8
<1><aad>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x30b): xlat_data
DW_AT_byte_size   : 12
DW_AT_decl_file   : 19
DW_AT_decl_line   : 51
DW_AT_decl_column : 8
DW_AT_sibling     : <0xad9>
<2><aba>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : val
DW_AT_decl_file   : 19
DW_AT_decl_line   : 52
DW_AT_decl_column : 11
DW_AT_type        : <0x116>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><ac9>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : str
DW_AT_decl_file   : 19
DW_AT_decl_line   : 53
DW_AT_decl_column : 14
DW_AT_type        : <0x1c9>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><ad9>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xaad>
<1><ade>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x22): xlat
DW_AT_byte_size   : 24
DW_AT_decl_file   : 19
DW_AT_decl_line   : 56
DW_AT_decl_column : 8
DW_AT_sibling     : <0xb37>
<2><aeb>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1052): data
DW_AT_decl_file   : 19
DW_AT_decl_line   : 57
DW_AT_decl_column : 26
DW_AT_type        : <0xb3c>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><afa>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x7bf): flags_strsz
DW_AT_decl_file   : 19
DW_AT_decl_line   : 58
DW_AT_decl_column : 9
DW_AT_type        : <0x122>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><b09>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xaa8): size
DW_AT_decl_file   : 19
DW_AT_decl_line   : 59
DW_AT_decl_column : 11
DW_AT_type        : <0x10a>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><b18>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x195): type
DW_AT_decl_file   : 19
DW_AT_decl_line   : 60
DW_AT_decl_column : 17
DW_AT_type        : <0xa4b>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><b27>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x659): flags_mask
DW_AT_decl_file   : 19
DW_AT_decl_line   : 61
DW_AT_decl_column : 11
DW_AT_type        : <0x116>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><b37>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xade>
<1><b3c>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xad9>
<1><b42>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xb37>
DW_AT_sibling     : <0xb4d>
<2><b4b>
Abbrev Number: 18 (DW_TAG_subrange_type)
<1><b4d>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xb42>
<1><b52>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdf5): addrfams
DW_AT_decl_file   : 18
DW_AT_decl_line   : 406
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><b61>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xcc8): arp_hardware_types
DW_AT_decl_file   : 18
DW_AT_decl_line   : 407
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><b70>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf86): at_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 408
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><b7f>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x464): clocknames
DW_AT_decl_file   : 18
DW_AT_decl_line   : 409
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><b8e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf51): dirent_types
DW_AT_decl_file   : 18
DW_AT_decl_line   : 410
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><b9d>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x810): ethernet_protocols
DW_AT_decl_file   : 18
DW_AT_decl_line   : 411
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><bac>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x57f): inet_protocols
DW_AT_decl_file   : 18
DW_AT_decl_line   : 412
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><bbb>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x2aa): evdev_abs
DW_AT_decl_file   : 18
DW_AT_decl_line   : 413
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><bca>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x64e): audit_arch
DW_AT_decl_file   : 18
DW_AT_decl_line   : 414
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><bd9>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x99): evdev_ev
DW_AT_decl_file   : 18
DW_AT_decl_line   : 415
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><be8>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x445): iffflags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 416
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><bf7>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xb45): ip_type_of_services
DW_AT_decl_file   : 18
DW_AT_decl_line   : 417
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c06>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x5da): ipc_private
DW_AT_decl_file   : 18
DW_AT_decl_line   : 418
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c15>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x301): msg_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 419
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c24>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x109): netlink_protocols
DW_AT_decl_file   : 18
DW_AT_decl_line   : 420
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c33>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xecb): nl_bridge_vlan_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 421
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c42>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd6f): nl_netfilter_msg_types
DW_AT_decl_file   : 18
DW_AT_decl_line   : 422
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c51>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x216): nl_route_types
DW_AT_decl_file   : 18
DW_AT_decl_line   : 423
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c60>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe3a): open_access_modes
DW_AT_decl_file   : 18
DW_AT_decl_line   : 424
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c6f>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x79): open_mode_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 425
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c7e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xbd7): perf_type_id
DW_AT_decl_file   : 18
DW_AT_decl_line   : 426
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c8d>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdfe): pollflags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 427
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c9c>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x520): ptrace_cmds
DW_AT_decl_file   : 18
DW_AT_decl_line   : 428
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><cab>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x752): resource_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 429
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><cba>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x280): route_nexthop_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 430
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><cc9>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe60): routing_protocols
DW_AT_decl_file   : 18
DW_AT_decl_line   : 431
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><cd8>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x436): routing_scopes
DW_AT_decl_file   : 18
DW_AT_decl_line   : 432
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ce7>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd5d): routing_table_ids
DW_AT_decl_file   : 18
DW_AT_decl_line   : 433
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><cf6>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x5b7): routing_types
DW_AT_decl_file   : 18
DW_AT_decl_line   : 434
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d05>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1b9): rwf_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 435
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d14>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x78a): seccomp_filter_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 436
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d23>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x2c7): seccomp_ret_action
DW_AT_decl_file   : 18
DW_AT_decl_line   : 437
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d32>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x3ff): setns_types
DW_AT_decl_file   : 18
DW_AT_decl_line   : 438
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d41>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdea): sg_io_info
DW_AT_decl_file   : 18
DW_AT_decl_line   : 439
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d50>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xaeb): socketlayers
DW_AT_decl_file   : 18
DW_AT_decl_line   : 440
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d5f>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd3c): socktypes
DW_AT_decl_file   : 18
DW_AT_decl_line   : 441
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d6e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x9c5): tcp_state_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 442
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d7d>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x683): tcp_states
DW_AT_decl_file   : 18
DW_AT_decl_line   : 443
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d8c>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xfe3): whence_codes
DW_AT_decl_file   : 18
DW_AT_decl_line   : 444
DW_AT_decl_column : 26
DW_AT_type        : <0xb4d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d9b>
Abbrev Number: 28 (DW_TAG_enumeration_type)
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 18
DW_AT_decl_line   : 505
DW_AT_decl_column : 14
DW_AT_sibling     : <0xdbd>
<2><daa>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x8e0): CFLAG_NONE
DW_AT_const_value : 0
<2><db0>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x823): CFLAG_ONLY_STATS
DW_AT_const_value : 1
<2><db6>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xaf8): CFLAG_BOTH
DW_AT_const_value : 2
<1><dbd>
Abbrev Number: 29 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1085): cflag_t
DW_AT_decl_file   : 18
DW_AT_decl_line   : 509
DW_AT_decl_column : 3
DW_AT_type        : <0xd9b>
<1><dca>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc83): cflag
DW_AT_decl_file   : 18
DW_AT_decl_line   : 510
DW_AT_decl_column : 16
DW_AT_type        : <0xdbd>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><dd9>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x184): Tflag
DW_AT_decl_file   : 18
DW_AT_decl_line   : 511
DW_AT_decl_column : 13
DW_AT_type        : <0x576>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><de8>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x6e8): Tflag_scale
DW_AT_decl_file   : 18
DW_AT_decl_line   : 512
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><df7>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x79f): Tflag_width
DW_AT_decl_file   : 18
DW_AT_decl_line   : 513
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><e06>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdd6): iflag
DW_AT_decl_file   : 18
DW_AT_decl_line   : 514
DW_AT_decl_column : 13
DW_AT_type        : <0x576>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><e15>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x560): count_wallclock
DW_AT_decl_file   : 18
DW_AT_decl_line   : 515
DW_AT_decl_column : 13
DW_AT_type        : <0x576>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><e24>
Abbrev Number: 30 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x4a): path_set_item
DW_AT_byte_size   : 4
DW_AT_decl_file   : 18
DW_AT_decl_line   : 517
DW_AT_decl_column : 8
DW_AT_sibling     : <0xe43>
<2><e32>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc7): path
DW_AT_decl_file   : 18
DW_AT_decl_line   : 518
DW_AT_decl_column : 14
DW_AT_type        : <0x1c9>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><e43>
Abbrev Number: 30 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x68e): path_set
DW_AT_byte_size   : 12
DW_AT_decl_file   : 18
DW_AT_decl_line   : 522
DW_AT_decl_column : 15
DW_AT_sibling     : <0xe82>
<2><e51>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x615): paths_selected
DW_AT_decl_file   : 18
DW_AT_decl_line   : 523
DW_AT_decl_column : 24
DW_AT_type        : <0xe82>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><e61>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfd6): num_selected
DW_AT_decl_file   : 18
DW_AT_decl_line   : 524
DW_AT_decl_column : 9
DW_AT_type        : <0x122>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><e71>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xaa8): size
DW_AT_decl_file   : 18
DW_AT_decl_line   : 525
DW_AT_decl_column : 9
DW_AT_type        : <0x122>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><e82>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xe24>
<1><e88>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1025): global_path_set
DW_AT_decl_file   : 18
DW_AT_decl_line   : 526
DW_AT_decl_column : 3
DW_AT_type        : <0xe43>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><e97>
Abbrev Number: 31 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0xf3e): xflag_opts
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 18
DW_AT_decl_line   : 528
DW_AT_decl_column : 6
DW_AT_sibling     : <0xec9>
<2><eaa>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x985): HEXSTR_NONE
DW_AT_const_value : 0
<2><eb0>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xf68): HEXSTR_NON_ASCII
DW_AT_const_value : 1
<2><eb6>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x861): HEXSTR_ALL
DW_AT_const_value : 2
<2><ebc>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x5a0): HEXSTR_NON_ASCII_CHARS
DW_AT_const_value : 3
<2><ec2>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xff0): NUM_HEXSTR_OPTS
DW_AT_const_value : 4
<1><ec9>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdb0): xflag
DW_AT_decl_file   : 18
DW_AT_decl_line   : 541
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ed8>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd46): followfork
DW_AT_decl_file   : 18
DW_AT_decl_line   : 542
DW_AT_decl_column : 13
DW_AT_type        : <0x576>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ee7>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x315): output_separately
DW_AT_decl_file   : 18
DW_AT_decl_line   : 543
DW_AT_decl_column : 13
DW_AT_type        : <0x576>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ef6>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x225): stack_trace_enabled
DW_AT_decl_file   : 18
DW_AT_decl_line   : 546
DW_AT_decl_column : 13
DW_AT_type        : <0x576>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f05>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x58e): ptrace_setoptions
DW_AT_decl_file   : 18
DW_AT_decl_line   : 550
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f14>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x97a): max_strlen
DW_AT_decl_file   : 18
DW_AT_decl_line   : 551
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f23>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x9a8): os_release
DW_AT_decl_file   : 18
DW_AT_decl_line   : 552
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f32>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x62b): xlat_verbosity
DW_AT_decl_file   : 18
DW_AT_decl_line   : 914
DW_AT_decl_column : 24
DW_AT_type        : <0xa70>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f41>
Abbrev Number: 31 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x543): xlat_style_private_flag_bits
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 18
DW_AT_decl_line   : 934
DW_AT_decl_column : 6
DW_AT_sibling     : <0xf6d>
<2><f54>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x294): PAF_PRINT_INDICES_BIT
DW_AT_const_value : 5
<2><f5a>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xa5f): PAF_ARRAY_TRUNCATED_BIT
DW_AT_const_value : 6
<2><f60>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x3b1): PXF_DEFAULT_STR_BIT
DW_AT_const_value : 7
<2><f66>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xc0e): SPFF_AUXSTR_MODE_BIT
DW_AT_const_value : 8
<1><f6d>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x77d>
<1><f73>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xf6d>
<1><f78>
Abbrev Number: 31 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0xcdb): find_xlat_flag_bits
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1438
DW_AT_decl_column : 6
DW_AT_sibling     : <0xf92>
<2><f8b>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x89e): FXL_CASE_SENSITIVE_BIT
DW_AT_const_value : 0
<1><f92>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x956): printing_tcp
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1684
DW_AT_decl_column : 20
DW_AT_type        : <0xf6d>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fa1>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x50b): errnoent
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1882
DW_AT_decl_column : 26
DW_AT_type        : <0x4aa>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fb0>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x7ab): signalent
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1883
DW_AT_decl_column : 26
DW_AT_type        : <0x4aa>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fbf>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe24): nerrnos
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1884
DW_AT_decl_column : 27
DW_AT_type        : <0x32>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fce>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xfbf): nsignals
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1885
DW_AT_decl_column : 27
DW_AT_type        : <0x32>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fdd>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x65f>
DW_AT_sibling     : <0xfe8>
<2><fe6>
Abbrev Number: 18 (DW_TAG_subrange_type)
<1><fe8>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xfdd>
<1><fed>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xca0): sysent0
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1887
DW_AT_decl_column : 28
DW_AT_type        : <0xfe8>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ffc>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x6c6>
DW_AT_sibling     : <0x1007>
<2><1005>
Abbrev Number: 18 (DW_TAG_subrange_type)
<1><1007>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xffc>
<1><100c>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x101b): ioctlent0
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1888
DW_AT_decl_column : 30
DW_AT_type        : <0x1007>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><101b>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x424): personality_names
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1890
DW_AT_decl_column : 26
DW_AT_type        : <0x4aa>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><102a>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x7cb): sysent
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1893
DW_AT_decl_column : 29
DW_AT_type        : <0x9db>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1039>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc23): ioctlent
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1894
DW_AT_decl_column : 31
DW_AT_type        : <0x1048>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1048>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x6c6>
<1><104e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x7b5): nsyscalls
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1900
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><105d>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe4c): nioctlents
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1901
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><106c>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x32>
DW_AT_sibling     : <0x107c>
<2><1075>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 2
<1><107c>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x106c>
<1><1081>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xeab): nsyscall_vec
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1903
DW_AT_decl_column : 27
DW_AT_type        : <0x107c>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1090>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x9e1>
DW_AT_sibling     : <0x10a0>
<2><1099>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 2
<1><10a0>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1090>
<1><10a5>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x6d5): sysent_vec
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1904
DW_AT_decl_column : 35
DW_AT_type        : <0x10a0>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><10b4>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x360): inject_vec
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1905
DW_AT_decl_column : 28
DW_AT_type        : <0x9e6>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><10c3>
Abbrev Number: 30 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xd2f): audit_arch_t
DW_AT_byte_size   : 8
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1907
DW_AT_decl_column : 8
DW_AT_sibling     : <0x10f2>
<2><10d1>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x535): arch
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1908
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><10e1>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x93c): flag
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1909
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><10f2>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x10c3>
<1><10f7>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x10f2>
DW_AT_sibling     : <0x1107>
<2><1100>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 2
<1><1107>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x10f7>
<1><110c>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x88f): audit_arch_vec
DW_AT_decl_file   : 18
DW_AT_decl_line   : 1912
DW_AT_decl_column : 34
DW_AT_type        : <0x1107>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><111b>
Abbrev Number: 32 (DW_TAG_structure_type)
DW_AT_byte_size   : 180
DW_AT_decl_file   : 20
DW_AT_decl_line   : 2
DW_AT_decl_column : 9
DW_AT_sibling     : <0x13d5>
<2><1124>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d1): block_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 3
DW_AT_decl_column : 8
DW_AT_type        : <0x13ef>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1133>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9fe): btrfs_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 6
DW_AT_decl_column : 8
DW_AT_type        : <0x13ef>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><1142>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x664): evdev_write_ioctl_mpers
DW_AT_decl_file   : 20
DW_AT_decl_line   : 9
DW_AT_decl_column : 8
DW_AT_type        : <0x13ef>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><1151>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x63a): get_sock_fprog_size
DW_AT_decl_file   : 20
DW_AT_decl_line   : 12
DW_AT_decl_column : 17
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><1160>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a0): fetch_bpf_fprog
DW_AT_decl_file   : 20
DW_AT_decl_line   : 15
DW_AT_decl_column : 10
DW_AT_type        : <0x141b>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><116f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x87c): fetch_struct_flock
DW_AT_decl_file   : 20
DW_AT_decl_line   : 18
DW_AT_decl_column : 10
DW_AT_type        : <0x141b>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><117e>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc49): fetch_struct_flock64
DW_AT_decl_file   : 20
DW_AT_decl_line   : 21
DW_AT_decl_column : 10
DW_AT_type        : <0x141b>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><118d>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x151): fetch_struct_iovec
DW_AT_decl_file   : 20
DW_AT_decl_line   : 24
DW_AT_decl_column : 10
DW_AT_type        : <0x141b>
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><119c>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x61): fetch_keyctl_kdf_params
DW_AT_decl_file   : 20
DW_AT_decl_line   : 27
DW_AT_decl_column : 8
DW_AT_type        : <0x1447>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><11ab>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x5c5): fetch_struct_mmsghdr
DW_AT_decl_file   : 20
DW_AT_decl_line   : 30
DW_AT_decl_column : 8
DW_AT_type        : <0x1467>
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><11ba>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd19): sizeof_struct_mmsghdr
DW_AT_decl_file   : 20
DW_AT_decl_line   : 33
DW_AT_decl_column : 17
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><11c9>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa77): fetch_struct_msghdr
DW_AT_decl_file   : 20
DW_AT_decl_line   : 36
DW_AT_decl_column : 8
DW_AT_type        : <0x1467>
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><11d8>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x697): fetch_struct_stat
DW_AT_decl_file   : 20
DW_AT_decl_line   : 39
DW_AT_decl_column : 10
DW_AT_type        : <0x1498>
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><11e7>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa24): fetch_struct_stat64
DW_AT_decl_file   : 20
DW_AT_decl_line   : 42
DW_AT_decl_column : 10
DW_AT_type        : <0x1498>
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><11f6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x40b): fetch_struct_statfs
DW_AT_decl_file   : 20
DW_AT_decl_line   : 45
DW_AT_decl_column : 10
DW_AT_type        : <0x14c9>
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><1205>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x7dd): fetch_struct_statfs64
DW_AT_decl_file   : 20
DW_AT_decl_line   : 48
DW_AT_decl_column : 10
DW_AT_type        : <0x14ee>
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><1214>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x11b): fetch_struct_quotastat
DW_AT_decl_file   : 20
DW_AT_decl_line   : 51
DW_AT_decl_column : 10
DW_AT_type        : <0x150e>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><1223>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa2): hdio_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 54
DW_AT_decl_column : 8
DW_AT_type        : <0x13ef>
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><1232>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa3d): kd_mpers_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 57
DW_AT_decl_column : 8
DW_AT_type        : <0x13ef>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><1241>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x99d): loop_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 60
DW_AT_decl_column : 8
DW_AT_type        : <0x152e>
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<2><1250>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x86c): mtd_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 63
DW_AT_decl_column : 8
DW_AT_type        : <0x13ef>
DW_AT_data_member_location: 2 byte block: 23 50 	(DW_OP_plus_uconst: 80)
<2><125f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcbd): perf_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 66
DW_AT_decl_column : 8
DW_AT_type        : <0x13ef>
DW_AT_data_member_location: 2 byte block: 23 54 	(DW_OP_plus_uconst: 84)
<2><126e>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x742): print_group_req
DW_AT_decl_file   : 20
DW_AT_decl_line   : 69
DW_AT_decl_column : 9
DW_AT_type        : <0x154a>
DW_AT_data_member_location: 2 byte block: 23 58 	(DW_OP_plus_uconst: 88)
<2><127d>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3dd): print_kernel_sigset
DW_AT_decl_file   : 20
DW_AT_decl_line   : 72
DW_AT_decl_column : 9
DW_AT_type        : <0x1561>
DW_AT_data_member_location: 2 byte block: 23 5c 	(DW_OP_plus_uconst: 92)
<2><128c>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdca): printmqattr
DW_AT_decl_file   : 20
DW_AT_decl_line   : 75
DW_AT_decl_column : 9
DW_AT_type        : <0x157d>
DW_AT_data_member_location: 2 byte block: 23 60 	(DW_OP_plus_uconst: 96)
<2><129b>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe8e): tprint_msgbuf
DW_AT_decl_file   : 20
DW_AT_decl_line   : 78
DW_AT_decl_column : 9
DW_AT_type        : <0x1599>
DW_AT_data_member_location: 2 byte block: 23 64 	(DW_OP_plus_uconst: 100)
<2><12aa>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8f0): decode_sg_req_info
DW_AT_decl_file   : 20
DW_AT_decl_line   : 81
DW_AT_decl_column : 8
DW_AT_type        : <0x15b4>
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<2><12b9>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x570): print_sigevent
DW_AT_decl_file   : 20
DW_AT_decl_line   : 84
DW_AT_decl_column : 9
DW_AT_type        : <0x15cb>
DW_AT_data_member_location: 2 byte block: 23 6c 	(DW_OP_plus_uconst: 108)
<2><12c8>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcc): print_struct_timeval
DW_AT_decl_file   : 20
DW_AT_decl_line   : 87
DW_AT_decl_column : 9
DW_AT_type        : <0x15dd>
DW_AT_data_member_location: 2 byte block: 23 70 	(DW_OP_plus_uconst: 112)
<2><12d7>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4d0): print_struct_timeval_data_size
DW_AT_decl_file   : 20
DW_AT_decl_line   : 90
DW_AT_decl_column : 10
DW_AT_type        : <0x15f8>
DW_AT_data_member_location: 2 byte block: 23 74 	(DW_OP_plus_uconst: 116)
<2><12e6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd91): print_timeval
DW_AT_decl_file   : 20
DW_AT_decl_line   : 93
DW_AT_decl_column : 8
DW_AT_type        : <0x15b4>
DW_AT_data_member_location: 2 byte block: 23 78 	(DW_OP_plus_uconst: 120)
<2><12f5>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf20): print_timeval_utimes
DW_AT_decl_file   : 20
DW_AT_decl_line   : 96
DW_AT_decl_column : 8
DW_AT_type        : <0x15b4>
DW_AT_data_member_location: 2 byte block: 23 7c 	(DW_OP_plus_uconst: 124)
<2><1304>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xefa): sprint_timeval
DW_AT_decl_file   : 20
DW_AT_decl_line   : 99
DW_AT_decl_column : 17
DW_AT_type        : <0x1613>
DW_AT_data_member_location: 3 byte block: 23 80 1 	(DW_OP_plus_uconst: 128)
<2><1314>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x963): print_itimerval
DW_AT_decl_file   : 20
DW_AT_decl_line   : 102
DW_AT_decl_column : 8
DW_AT_type        : <0x15b4>
DW_AT_data_member_location: 3 byte block: 23 84 1 	(DW_OP_plus_uconst: 132)
<2><1324>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x702): printrusage
DW_AT_decl_file   : 20
DW_AT_decl_line   : 105
DW_AT_decl_column : 9
DW_AT_type        : <0x15cb>
DW_AT_data_member_location: 3 byte block: 23 88 1 	(DW_OP_plus_uconst: 136)
<2><1334>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x141): printsiginfo_at
DW_AT_decl_file   : 20
DW_AT_decl_line   : 108
DW_AT_decl_column : 9
DW_AT_type        : <0x15cb>
DW_AT_data_member_location: 3 byte block: 23 8c 1 	(DW_OP_plus_uconst: 140)
<2><1344>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4bc): print_siginfo_array
DW_AT_decl_file   : 20
DW_AT_decl_line   : 111
DW_AT_decl_column : 9
DW_AT_type        : <0x1599>
DW_AT_data_member_location: 3 byte block: 23 90 1 	(DW_OP_plus_uconst: 144)
<2><1354>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x46f): decode_prstatus_regset
DW_AT_decl_file   : 20
DW_AT_decl_line   : 114
DW_AT_decl_column : 9
DW_AT_type        : <0x1599>
DW_AT_data_member_location: 3 byte block: 23 94 1 	(DW_OP_plus_uconst: 148)
<2><1364>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x834): decode_fpregset
DW_AT_decl_file   : 20
DW_AT_decl_line   : 117
DW_AT_decl_column : 9
DW_AT_type        : <0x1599>
DW_AT_data_member_location: 3 byte block: 23 98 1 	(DW_OP_plus_uconst: 152)
<2><1374>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x852): decode_pt_regs
DW_AT_decl_file   : 20
DW_AT_decl_line   : 120
DW_AT_decl_column : 9
DW_AT_type        : <0x15cb>
DW_AT_data_member_location: 3 byte block: 23 9c 1 	(DW_OP_plus_uconst: 156)
<2><1384>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x327): decode_pt_fpregs
DW_AT_decl_file   : 20
DW_AT_decl_line   : 123
DW_AT_decl_column : 9
DW_AT_type        : <0x15cb>
DW_AT_data_member_location: 3 byte block: 23 a0 1 	(DW_OP_plus_uconst: 160)
<2><1394>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x94c): rtc_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 126
DW_AT_decl_column : 8
DW_AT_type        : <0x13ef>
DW_AT_data_member_location: 3 byte block: 23 a4 1 	(DW_OP_plus_uconst: 164)
<2><13a4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfa9): decode_sg_io_v3
DW_AT_decl_file   : 20
DW_AT_decl_line   : 129
DW_AT_decl_column : 8
DW_AT_type        : <0x15b4>
DW_AT_data_member_location: 3 byte block: 23 a8 1 	(DW_OP_plus_uconst: 168)
<2><13b4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdbf): sock_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 132
DW_AT_decl_column : 8
DW_AT_type        : <0x152e>
DW_AT_data_member_location: 3 byte block: 23 ac 1 	(DW_OP_plus_uconst: 172)
<2><13c4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x275): v4l2_ioctl
DW_AT_decl_file   : 20
DW_AT_decl_line   : 135
DW_AT_decl_column : 8
DW_AT_type        : <0x13ef>
DW_AT_data_member_location: 3 byte block: 23 b0 1 	(DW_OP_plus_uconst: 176)
<1><13d5>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x13ef>
<2><13df>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><13e4>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x32>
<2><13e9>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<1><13ef>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x13d5>
<1><13f5>
Abbrev Number: 34 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x2b>
<1><13fb>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x13f5>
<1><1401>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x576>
DW_AT_sibling     : <0x141b>
<2><140b>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><1410>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><1415>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xcf>
<1><141b>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1401>
<1><1421>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x143b>
<2><142b>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><1430>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5a6>
<2><1435>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x143b>
<1><143b>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1441>
<1><1441>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1ed): strace_keyctl_kdf_params
DW_AT_declaration : 1
<1><1447>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1421>
<1><144d>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x1467>
<2><1457>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><145c>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><1461>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xcf>
<1><1467>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x144d>
<1><146d>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x576>
DW_AT_sibling     : <0x1487>
<2><1477>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><147c>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><1481>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x148d>
<1><1487>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1492>
<1><148d>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1487>
<1><1492>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1063): strace_stat
DW_AT_declaration : 1
<1><1498>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x146d>
<1><149e>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x576>
DW_AT_sibling     : <0x14b8>
<2><14a8>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><14ad>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><14b2>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x14be>
<1><14b8>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x14c3>
<1><14be>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x14b8>
<1><14c3>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x103f): strace_statfs
DW_AT_declaration : 1
<1><14c9>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x149e>
<1><14cf>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x576>
DW_AT_sibling     : <0x14ee>
<2><14d9>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><14de>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><14e3>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><14e8>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x14be>
<1><14ee>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x14cf>
<1><14f4>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x576>
DW_AT_sibling     : <0x150e>
<2><14fe>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><1503>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><1508>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xcd>
<1><150e>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x14f4>
<1><1514>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x152e>
<2><151e>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf6d>
<2><1523>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x32>
<2><1528>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<1><152e>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1514>
<1><1534>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x154a>
<2><153a>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><153f>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><1544>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x6b>
<1><154a>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1534>
<1><1550>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x1561>
<2><1556>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf6d>
<2><155b>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<1><1561>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1550>
<1><1567>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x157d>
<2><156d>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><1572>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><1577>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x57d>
<1><157d>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1567>
<1><1583>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x1599>
<2><1589>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><158e>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><1593>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<1><1599>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1583>
<1><159f>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x15b4>
<2><15a9>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><15ae>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<1><15b4>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x159f>
<1><15ba>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x15cb>
<2><15c0>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><15c5>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<1><15cb>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x15ba>
<1><15d1>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x15dd>
<2><15d7>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x1d4>
<1><15dd>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x15d1>
<1><15e3>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x576>
DW_AT_sibling     : <0x15f8>
<2><15ed>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x1d4>
<2><15f2>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x12e>
<1><15f8>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x15e3>
<1><15fe>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x1c9>
DW_AT_sibling     : <0x1613>
<2><1608>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf73>
<2><160d>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<1><1613>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x15fe>
<1><1619>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1dd): struct_printers
DW_AT_decl_file   : 20
DW_AT_decl_line   : 138
DW_AT_decl_column : 3
DW_AT_type        : <0x111b>
<1><1625>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1619>
<1><162a>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x20d): printers
DW_AT_decl_file   : 20
DW_AT_decl_line   : 139
DW_AT_decl_column : 31
DW_AT_type        : <0x1638>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1638>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1625>
<1><163e>
Abbrev Number: 32 (DW_TAG_structure_type)
DW_AT_byte_size   : 12
DW_AT_decl_file   : 21
DW_AT_decl_line   : 14
DW_AT_decl_column : 9
DW_AT_sibling     : <0x1684>
<2><1647>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xef4): d_ino
DW_AT_decl_file   : 21
DW_AT_decl_line   : 15
DW_AT_decl_column : 17
DW_AT_type        : <0x5a6>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><1656>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xde4): d_off
DW_AT_decl_file   : 21
DW_AT_decl_line   : 16
DW_AT_decl_column : 17
DW_AT_type        : <0x5a6>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><1665>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe57): d_reclen
DW_AT_decl_file   : 21
DW_AT_decl_line   : 17
DW_AT_decl_column : 17
DW_AT_type        : <0x24>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><1674>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x486): d_name
DW_AT_decl_file   : 21
DW_AT_decl_line   : 18
DW_AT_decl_column : 8
DW_AT_type        : <0x40e>
DW_AT_data_member_location: 2 byte block: 23 a 	(DW_OP_plus_uconst: 10)
<1><1684>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x903): kernel_dirent_t
DW_AT_decl_file   : 21
DW_AT_decl_line   : 19
DW_AT_decl_column : 3
DW_AT_type        : <0x163e>
<1><1690>
Abbrev Number: 35 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe72): mpers_target_var
DW_AT_decl_file   : 22
DW_AT_decl_line   : 17
DW_AT_decl_column : 17
DW_AT_type        : <0x1684>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
