<1><1d>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 8	(unsigned char)
DW_AT_name        : (indirect string, offset: 0x3a1): unsigned char
<1><24>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xf61): short unsigned int
<1><2b>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x8c3): unsigned int
<1><32>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x2b>
<1><37>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0x6d6): long unsigned int
<1><3e>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x352): signed char
<1><45>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x255): __uint8_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 37
DW_AT_decl_column : 23
DW_AT_type        : <0x1d>
<1><51>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 2
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0xd8d): short int
<1><58>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x473): __uint16_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 39
DW_AT_decl_column : 28
DW_AT_type        : <0x24>
<1><64>
Abbrev Number: 5 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : int
<1><6b>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x64>
<1><70>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x7c9): __uint32_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 41
DW_AT_decl_column : 22
DW_AT_type        : <0x2b>
<1><7c>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x7f9): long long int
<1><83>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x6bc): __uint64_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 47
DW_AT_decl_column : 46
DW_AT_type        : <0x8f>
<1><8f>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 8
DW_AT_encoding    : 7	(unsigned)
DW_AT_name        : (indirect string, offset: 0xa94): long long unsigned int
<1><96>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x72a): __quad_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 55
DW_AT_decl_column : 37
DW_AT_type        : <0x7c>
<1><a2>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xaca): __off_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 140
DW_AT_decl_column : 25
DW_AT_type        : <0xae>
<1><ae>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 4
DW_AT_encoding    : 5	(signed)
DW_AT_name        : (indirect string, offset: 0x2bb): long int
<1><b5>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xc95): __off64_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 141
DW_AT_decl_column : 27
DW_AT_type        : <0x96>
<1><c1>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xbec): __time_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 148
DW_AT_decl_column : 26
DW_AT_type        : <0xae>
<1><cd>
Abbrev Number: 6 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
<1><cf>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xcd>
<1><d4>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x3df): __syscall_slong_t
DW_AT_decl_file   : 1
DW_AT_decl_line   : 184
DW_AT_decl_column : 33
DW_AT_type        : <0xae>
<1><e0>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xe6>
<1><e6>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 6	(signed char)
DW_AT_name        : (indirect string, offset: 0x439): char
<1><ed>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xe6>
<1><f2>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x35e): uint8_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 24
DW_AT_decl_column : 19
DW_AT_type        : <0x45>
<1><fe>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xab5): uint16_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 25
DW_AT_decl_column : 20
DW_AT_type        : <0x58>
<1><10a>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xf07): uint32_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 26
DW_AT_decl_column : 20
DW_AT_type        : <0x70>
<1><116>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xd9d): uint64_t
DW_AT_decl_file   : 2
DW_AT_decl_line   : 27
DW_AT_decl_column : 20
DW_AT_type        : <0x83>
<1><122>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x100): time_t
DW_AT_decl_file   : 3
DW_AT_decl_line   : 7
DW_AT_decl_column : 18
DW_AT_type        : <0xc1>
<1><12e>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x39): size_t
DW_AT_decl_file   : 4
DW_AT_decl_line   : 209
DW_AT_decl_column : 23
DW_AT_type        : <0x2b>
<1><13a>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x12e>
<1><13f>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xa3d): timespec
DW_AT_byte_size   : 8
DW_AT_decl_file   : 5
DW_AT_decl_line   : 9
DW_AT_decl_column : 8
DW_AT_sibling     : <0x16b>
<2><14c>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x102e): tv_sec
DW_AT_decl_file   : 5
DW_AT_decl_line   : 11
DW_AT_decl_column : 12
DW_AT_type        : <0xc1>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><15b>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdc3): tv_nsec
DW_AT_decl_file   : 5
DW_AT_decl_line   : 12
DW_AT_decl_column : 21
DW_AT_type        : <0xd4>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><16b>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 12
DW_AT_encoding    : 4	(float)
DW_AT_name        : (indirect string, offset: 0x9ff): long double
<1><172>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 16
DW_AT_encoding    : 4	(float)
DW_AT_name        : (indirect string, offset: 0xf30): _Float128
<1><179>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x272): __environ
DW_AT_decl_file   : 6
DW_AT_decl_line   : 546
DW_AT_decl_column : 15
DW_AT_type        : <0x188>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><188>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xe0>
<1><18e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x399): environ
DW_AT_decl_file   : 6
DW_AT_decl_line   : 548
DW_AT_decl_column : 15
DW_AT_type        : <0x188>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><19d>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf4b): optarg
DW_AT_decl_file   : 7
DW_AT_decl_line   : 36
DW_AT_decl_column : 14
DW_AT_type        : <0xe0>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1ab>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x68f): optind
DW_AT_decl_file   : 7
DW_AT_decl_line   : 50
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1b9>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xbdb): opterr
DW_AT_decl_file   : 7
DW_AT_decl_line   : 55
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1c7>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xa7a): optopt
DW_AT_decl_file   : 7
DW_AT_decl_line   : 59
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1d5>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xed>
<1><1db>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1d5>
<1><1e0>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1e6>
<1><1e6>
Abbrev Number: 12 (DW_TAG_const_type)
<1><1e7>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x366): _IO_FILE
DW_AT_byte_size   : 148
DW_AT_decl_file   : 8
DW_AT_decl_line   : 245
DW_AT_decl_column : 8
DW_AT_sibling     : <0x3bf>
<2><1f4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x95a): _flags
DW_AT_decl_file   : 8
DW_AT_decl_line   : 246
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><203>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4c2): _IO_read_ptr
DW_AT_decl_file   : 8
DW_AT_decl_line   : 251
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><212>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xebf): _IO_read_end
DW_AT_decl_file   : 8
DW_AT_decl_line   : 252
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><221>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x707): _IO_read_base
DW_AT_decl_file   : 8
DW_AT_decl_line   : 253
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><230>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x139): _IO_write_base
DW_AT_decl_file   : 8
DW_AT_decl_line   : 254
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><23f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf9a): _IO_write_ptr
DW_AT_decl_file   : 8
DW_AT_decl_line   : 255
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><24e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x83b): _IO_write_end
DW_AT_decl_file   : 8
DW_AT_decl_line   : 256
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><25e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8ac): _IO_buf_base
DW_AT_decl_file   : 8
DW_AT_decl_line   : 257
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><26e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd38): _IO_buf_end
DW_AT_decl_file   : 8
DW_AT_decl_line   : 258
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><27e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1ca): _IO_save_base
DW_AT_decl_file   : 8
DW_AT_decl_line   : 260
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><28e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc50): _IO_backup_base
DW_AT_decl_file   : 8
DW_AT_decl_line   : 261
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><29e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xba): _IO_save_end
DW_AT_decl_file   : 8
DW_AT_decl_line   : 262
DW_AT_decl_column : 9
DW_AT_type        : <0xe0>
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><2ae>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x54d): _markers
DW_AT_decl_file   : 8
DW_AT_decl_line   : 264
DW_AT_decl_column : 22
DW_AT_type        : <0x40e>
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><2be>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x20d): _chain
DW_AT_decl_file   : 8
DW_AT_decl_line   : 266
DW_AT_decl_column : 20
DW_AT_type        : <0x414>
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><2ce>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf1b): _fileno
DW_AT_decl_file   : 8
DW_AT_decl_line   : 268
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><2de>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6f3): _flags2
DW_AT_decl_file   : 8
DW_AT_decl_line   : 272
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><2ee>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x775): _old_offset
DW_AT_decl_file   : 8
DW_AT_decl_line   : 274
DW_AT_decl_column : 13
DW_AT_type        : <0xa2>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><2fe>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x240): _cur_column
DW_AT_decl_file   : 8
DW_AT_decl_line   : 278
DW_AT_decl_column : 18
DW_AT_type        : <0x24>
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><30e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xde9): _vtable_offset
DW_AT_decl_file   : 8
DW_AT_decl_line   : 279
DW_AT_decl_column : 15
DW_AT_type        : <0x3e>
DW_AT_data_member_location: 2 byte block: 23 46 	(DW_OP_plus_uconst: 70)
<2><31e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc60): _shortbuf
DW_AT_decl_file   : 8
DW_AT_decl_line   : 280
DW_AT_decl_column : 8
DW_AT_type        : <0x41a>
DW_AT_data_member_location: 2 byte block: 23 47 	(DW_OP_plus_uconst: 71)
<2><32e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x17a): _lock
DW_AT_decl_file   : 8
DW_AT_decl_line   : 284
DW_AT_decl_column : 15
DW_AT_type        : <0x42a>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><33e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x620): _offset
DW_AT_decl_file   : 8
DW_AT_decl_line   : 293
DW_AT_decl_column : 15
DW_AT_type        : <0xb5>
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<2><34e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8fa): __pad1
DW_AT_decl_file   : 8
DW_AT_decl_line   : 301
DW_AT_decl_column : 9
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 54 	(DW_OP_plus_uconst: 84)
<2><35e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x901): __pad2
DW_AT_decl_file   : 8
DW_AT_decl_line   : 302
DW_AT_decl_column : 9
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 58 	(DW_OP_plus_uconst: 88)
<2><36e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x908): __pad3
DW_AT_decl_file   : 8
DW_AT_decl_line   : 303
DW_AT_decl_column : 9
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 5c 	(DW_OP_plus_uconst: 92)
<2><37e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x90f): __pad4
DW_AT_decl_file   : 8
DW_AT_decl_line   : 304
DW_AT_decl_column : 9
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 60 	(DW_OP_plus_uconst: 96)
<2><38e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x916): __pad5
DW_AT_decl_file   : 8
DW_AT_decl_line   : 306
DW_AT_decl_column : 10
DW_AT_type        : <0x12e>
DW_AT_data_member_location: 2 byte block: 23 64 	(DW_OP_plus_uconst: 100)
<2><39e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x97e): _mode
DW_AT_decl_file   : 8
DW_AT_decl_line   : 307
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<2><3ae>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x721): _unused2
DW_AT_decl_file   : 8
DW_AT_decl_line   : 309
DW_AT_decl_column : 8
DW_AT_type        : <0x430>
DW_AT_data_member_location: 2 byte block: 23 6c 	(DW_OP_plus_uconst: 108)
<1><3bf>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xa1f): FILE
DW_AT_decl_file   : 9
DW_AT_decl_line   : 7
DW_AT_decl_column : 25
DW_AT_type        : <0x1e7>
<1><3cb>
Abbrev Number: 14 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x468): _IO_lock_t
DW_AT_decl_file   : 8
DW_AT_decl_line   : 154
DW_AT_decl_column : 14
<1><3d3>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x310): _IO_marker
DW_AT_byte_size   : 12
DW_AT_decl_file   : 8
DW_AT_decl_line   : 160
DW_AT_decl_column : 8
DW_AT_sibling     : <0x40e>
<2><3e0>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc8f): _next
DW_AT_decl_file   : 8
DW_AT_decl_line   : 161
DW_AT_decl_column : 22
DW_AT_type        : <0x40e>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><3ef>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x91d): _sbuf
DW_AT_decl_file   : 8
DW_AT_decl_line   : 162
DW_AT_decl_column : 20
DW_AT_type        : <0x414>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><3fe>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x502): _pos
DW_AT_decl_file   : 8
DW_AT_decl_line   : 166
DW_AT_decl_column : 7
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><40e>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x3d3>
<1><414>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1e7>
<1><41a>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xe6>
DW_AT_sibling     : <0x42a>
<2><423>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 0
<1><42a>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x3cb>
<1><430>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xe6>
DW_AT_sibling     : <0x440>
<2><439>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 39
<1><440>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x40b): _IO_FILE_plus
DW_AT_declaration : 1
<1><446>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x6c7): _IO_2_1_stdin_
DW_AT_decl_file   : 8
DW_AT_decl_line   : 319
DW_AT_decl_column : 29
DW_AT_type        : <0x440>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><455>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc70): _IO_2_1_stdout_
DW_AT_decl_file   : 8
DW_AT_decl_line   : 320
DW_AT_decl_column : 29
DW_AT_type        : <0x440>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><464>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x89): _IO_2_1_stderr_
DW_AT_decl_file   : 8
DW_AT_decl_line   : 321
DW_AT_decl_column : 29
DW_AT_type        : <0x440>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><473>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x518): stdin
DW_AT_decl_file   : 10
DW_AT_decl_line   : 135
DW_AT_decl_column : 25
DW_AT_type        : <0x414>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><481>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf74): stdout
DW_AT_decl_file   : 10
DW_AT_decl_line   : 136
DW_AT_decl_column : 25
DW_AT_type        : <0x414>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><48f>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd86): stderr
DW_AT_decl_file   : 10
DW_AT_decl_line   : 137
DW_AT_decl_column : 25
DW_AT_type        : <0x414>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><49d>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x24c): sys_nerr
DW_AT_decl_file   : 11
DW_AT_decl_line   : 26
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4ab>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x1db>
DW_AT_sibling     : <0x4b6>
<2><4b4>
Abbrev Number: 18 (DW_TAG_subrange_type)
<1><4b6>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x4ab>
<1><4bb>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x527): sys_errlist
DW_AT_decl_file   : 11
DW_AT_decl_line   : 27
DW_AT_decl_column : 26
DW_AT_type        : <0x4b6>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4c9>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x25f): _sys_nerr
DW_AT_decl_file   : 11
DW_AT_decl_line   : 30
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4d7>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdf8): _sys_errlist
DW_AT_decl_file   : 11
DW_AT_decl_line   : 31
DW_AT_decl_column : 26
DW_AT_type        : <0x4b6>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4e5>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x5f9): program_invocation_name
DW_AT_decl_file   : 12
DW_AT_decl_line   : 45
DW_AT_decl_column : 14
DW_AT_type        : <0xe0>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><4f3>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xaf5): program_invocation_short_name
DW_AT_decl_file   : 12
DW_AT_decl_line   : 46
DW_AT_decl_column : 14
DW_AT_type        : <0xe0>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><501>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xe0>
DW_AT_sibling     : <0x511>
<2><50a>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 1
<1><511>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1b7): __tzname
DW_AT_decl_file   : 13
DW_AT_decl_line   : 159
DW_AT_decl_column : 14
DW_AT_type        : <0x501>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><51f>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe5b): __daylight
DW_AT_decl_file   : 13
DW_AT_decl_line   : 160
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><52d>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x36f): __timezone
DW_AT_decl_file   : 13
DW_AT_decl_line   : 161
DW_AT_decl_column : 17
DW_AT_type        : <0xae>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><53b>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x637): tzname
DW_AT_decl_file   : 13
DW_AT_decl_line   : 166
DW_AT_decl_column : 14
DW_AT_type        : <0x501>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><549>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xfe4): daylight
DW_AT_decl_file   : 13
DW_AT_decl_line   : 174
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><557>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x4ad): timezone
DW_AT_decl_file   : 13
DW_AT_decl_line   : 175
DW_AT_decl_column : 17
DW_AT_type        : <0xae>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><565>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xedb): getdate_err
DW_AT_decl_file   : 13
DW_AT_decl_line   : 280
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><574>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x928): debug_flag
DW_AT_decl_file   : 14
DW_AT_decl_line   : 20
DW_AT_decl_column : 13
DW_AT_type        : <0x582>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><582>
Abbrev Number: 2 (DW_TAG_base_type)
DW_AT_byte_size   : 1
DW_AT_encoding    : 2	(boolean)
DW_AT_name        : (indirect string, offset: 0x3f1): _Bool
<1><589>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x582>
<1><58e>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x9d5): __kernel_long_t
DW_AT_decl_file   : 15
DW_AT_decl_line   : 15
DW_AT_decl_column : 15
DW_AT_type        : <0xae>
<1><59a>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x507): __kernel_ulong_t
DW_AT_decl_file   : 15
DW_AT_decl_line   : 16
DW_AT_decl_column : 23
DW_AT_type        : <0x37>
<1><5a6>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x3bd): kernel_long_t
DW_AT_decl_file   : 16
DW_AT_decl_line   : 16
DW_AT_decl_column : 25
DW_AT_type        : <0x58e>
<1><5b2>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x7ea): kernel_ulong_t
DW_AT_decl_file   : 16
DW_AT_decl_line   : 17
DW_AT_decl_column : 26
DW_AT_type        : <0x59a>
<1><5be>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x5b2>
<1><5c3>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xb13): list_item
DW_AT_byte_size   : 8
DW_AT_decl_file   : 17
DW_AT_decl_line   : 92
DW_AT_decl_column : 8
DW_AT_sibling     : <0x5ef>
<2><5d0>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1029): prev
DW_AT_decl_file   : 17
DW_AT_decl_line   : 93
DW_AT_decl_column : 20
DW_AT_type        : <0x5ef>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><5df>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x101f): next
DW_AT_decl_file   : 17
DW_AT_decl_line   : 94
DW_AT_decl_column : 20
DW_AT_type        : <0x5ef>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><5ef>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x5c3>
<1><5f5>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x7c2): sysent
DW_AT_byte_size   : 20
DW_AT_decl_file   : 18
DW_AT_decl_line   : 11
DW_AT_decl_column : 16
DW_AT_sibling     : <0x64e>
<2><602>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf8b): nargs
DW_AT_decl_file   : 18
DW_AT_decl_line   : 12
DW_AT_decl_column : 11
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><611>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8b9): sys_flags
DW_AT_decl_file   : 18
DW_AT_decl_line   : 13
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><620>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : sen
DW_AT_decl_file   : 18
DW_AT_decl_line   : 14
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><62f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x307): sys_func
DW_AT_decl_file   : 18
DW_AT_decl_line   : 15
DW_AT_decl_column : 8
DW_AT_type        : <0x659>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><63e>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x269): sys_name
DW_AT_decl_file   : 18
DW_AT_decl_line   : 16
DW_AT_decl_column : 14
DW_AT_type        : <0x1d5>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><64e>
Abbrev Number: 20 (DW_TAG_subroutine_type)
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x659>
<2><657>
Abbrev Number: 21 (DW_TAG_unspecified_parameters)
<1><659>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x64e>
<1><65f>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xe0d): struct_sysent
DW_AT_decl_file   : 18
DW_AT_decl_line   : 17
DW_AT_decl_column : 3
DW_AT_type        : <0x5f5>
<1><66b>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x65f>
<1><670>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xcd6): current_personality
DW_AT_decl_file   : 19
DW_AT_decl_line   : 158
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><67e>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x764): current_wordsize
DW_AT_decl_file   : 19
DW_AT_decl_line   : 171
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><68c>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x99a): current_klongsize
DW_AT_decl_file   : 19
DW_AT_decl_line   : 176
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><69a>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xc0a): ioctlent
DW_AT_byte_size   : 8
DW_AT_decl_file   : 19
DW_AT_decl_line   : 217
DW_AT_decl_column : 16
DW_AT_sibling     : <0x6c6>
<2><6a7>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xeb8): symbol
DW_AT_decl_file   : 19
DW_AT_decl_line   : 218
DW_AT_decl_column : 14
DW_AT_type        : <0x1d5>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><6b6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc9f): code
DW_AT_decl_file   : 19
DW_AT_decl_line   : 219
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><6c6>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0xbcb): struct_ioctlent
DW_AT_decl_file   : 19
DW_AT_decl_line   : 220
DW_AT_decl_column : 3
DW_AT_type        : <0x69a>
<1><6d2>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x6c6>
<1><6d7>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x758): inject_data
DW_AT_byte_size   : 10
DW_AT_decl_file   : 19
DW_AT_decl_line   : 241
DW_AT_decl_column : 8
DW_AT_sibling     : <0x73f>
<2><6e4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4bc): flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 242
DW_AT_decl_column : 10
DW_AT_type        : <0xf2>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><6f3>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x86d): signo
DW_AT_decl_file   : 19
DW_AT_decl_line   : 243
DW_AT_decl_column : 10
DW_AT_type        : <0xf2>
DW_AT_data_member_location: 2 byte block: 23 1 	(DW_OP_plus_uconst: 1)
<2><702>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x107): rval_idx
DW_AT_decl_file   : 19
DW_AT_decl_line   : 244
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><711>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x40): delay_idx
DW_AT_decl_file   : 19
DW_AT_decl_line   : 245
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><720>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x53f): poke_idx
DW_AT_decl_file   : 19
DW_AT_decl_line   : 246
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<2><72f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x197): scno
DW_AT_decl_file   : 19
DW_AT_decl_line   : 247
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><73f>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xe1): inject_opts
DW_AT_byte_size   : 16
DW_AT_decl_file   : 19
DW_AT_decl_line   : 250
DW_AT_decl_column : 8
DW_AT_sibling     : <0x789>
<2><74c>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x978): first
DW_AT_decl_file   : 19
DW_AT_decl_line   : 251
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><75b>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1052): last
DW_AT_decl_file   : 19
DW_AT_decl_line   : 252
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 2 	(DW_OP_plus_uconst: 2)
<2><76a>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x394): step
DW_AT_decl_file   : 19
DW_AT_decl_line   : 253
DW_AT_decl_column : 11
DW_AT_type        : <0xfe>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><779>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1024): data
DW_AT_decl_file   : 19
DW_AT_decl_line   : 254
DW_AT_decl_column : 21
DW_AT_type        : <0x6d7>
DW_AT_data_member_location: 2 byte block: 23 6 	(DW_OP_plus_uconst: 6)
<1><789>
Abbrev Number: 22 (DW_TAG_structure_type)
DW_AT_name        : tcb
DW_AT_byte_size   : 196
DW_AT_decl_file   : 19
DW_AT_decl_line   : 262
DW_AT_decl_column : 8
DW_AT_sibling     : <0x9b3>
<2><797>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4bc): flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 263
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><7a7>
Abbrev Number: 23 (DW_TAG_member)
DW_AT_name        : pid
DW_AT_decl_file   : 19
DW_AT_decl_line   : 264
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><7b7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x58): qual_flg
DW_AT_decl_file   : 19
DW_AT_decl_line   : 265
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><7c7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x385): currpers
DW_AT_decl_file   : 19
DW_AT_decl_line   : 267
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><7d7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa72): u_error
DW_AT_decl_file   : 19
DW_AT_decl_line   : 269
DW_AT_decl_column : 16
DW_AT_type        : <0x37>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><7e7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x197): scno
DW_AT_decl_file   : 19
DW_AT_decl_line   : 270
DW_AT_decl_column : 17
DW_AT_type        : <0x5b2>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><7f7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xaab): true_scno
DW_AT_decl_file   : 19
DW_AT_decl_line   : 271
DW_AT_decl_column : 17
DW_AT_type        : <0x5b2>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><807>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a1): u_arg
DW_AT_decl_file   : 19
DW_AT_decl_line   : 272
DW_AT_decl_column : 17
DW_AT_type        : <0x9b3>
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><817>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8d0): u_rval
DW_AT_decl_file   : 19
DW_AT_decl_line   : 273
DW_AT_decl_column : 16
DW_AT_type        : <0x5a6>
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><827>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9f1): sys_func_rval
DW_AT_decl_file   : 19
DW_AT_decl_line   : 274
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><837>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc80): curcol
DW_AT_decl_file   : 19
DW_AT_decl_line   : 275
DW_AT_decl_column : 6
DW_AT_type        : <0x64>
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><847>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8e2): outf
DW_AT_decl_file   : 19
DW_AT_decl_line   : 276
DW_AT_decl_column : 8
DW_AT_type        : <0x9c3>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><857>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe90): staged_output_data
DW_AT_decl_file   : 19
DW_AT_decl_line   : 277
DW_AT_decl_column : 29
DW_AT_type        : <0x9cf>
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><867>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9bc): auxstr
DW_AT_decl_file   : 19
DW_AT_decl_line   : 279
DW_AT_decl_column : 14
DW_AT_type        : <0x1d5>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><877>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x180): _priv_data
DW_AT_decl_file   : 19
DW_AT_decl_line   : 280
DW_AT_decl_column : 8
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<2><887>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xbae): _free_priv_data
DW_AT_decl_file   : 19
DW_AT_decl_line   : 281
DW_AT_decl_column : 9
DW_AT_type        : <0x9e1>
DW_AT_data_member_location: 2 byte block: 23 50 	(DW_OP_plus_uconst: 80)
<2><897>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x191): s_ent
DW_AT_decl_file   : 19
DW_AT_decl_line   : 282
DW_AT_decl_column : 23
DW_AT_type        : <0x9e7>
DW_AT_data_member_location: 2 byte block: 23 54 	(DW_OP_plus_uconst: 84)
<2><8a7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x27): s_prev_ent
DW_AT_decl_file   : 19
DW_AT_decl_line   : 285
DW_AT_decl_column : 23
DW_AT_type        : <0x9e7>
DW_AT_data_member_location: 2 byte block: 23 58 	(DW_OP_plus_uconst: 88)
<2><8b7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x37a): inject_vec
DW_AT_decl_file   : 19
DW_AT_decl_line   : 286
DW_AT_decl_column : 22
DW_AT_type        : <0x9f2>
DW_AT_data_member_location: 2 byte block: 23 5c 	(DW_OP_plus_uconst: 92)
<2><8c7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x733): stime
DW_AT_decl_file   : 19
DW_AT_decl_line   : 287
DW_AT_decl_column : 18
DW_AT_type        : <0x13f>
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<2><8d7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x38e): ltime
DW_AT_decl_file   : 19
DW_AT_decl_line   : 288
DW_AT_decl_column : 18
DW_AT_type        : <0x13f>
DW_AT_data_member_location: 2 byte block: 23 70 	(DW_OP_plus_uconst: 112)
<2><8e7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf52): atime
DW_AT_decl_file   : 19
DW_AT_decl_line   : 289
DW_AT_decl_column : 18
DW_AT_type        : <0x13f>
DW_AT_data_member_location: 2 byte block: 23 78 	(DW_OP_plus_uconst: 120)
<2><8f7>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4b6): etime
DW_AT_decl_file   : 19
DW_AT_decl_line   : 290
DW_AT_decl_column : 18
DW_AT_type        : <0x13f>
DW_AT_data_member_location: 3 byte block: 23 80 1 	(DW_OP_plus_uconst: 128)
<2><908>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcea): delay_expiration_time
DW_AT_decl_file   : 19
DW_AT_decl_line   : 291
DW_AT_decl_column : 18
DW_AT_type        : <0x13f>
DW_AT_data_member_location: 3 byte block: 23 88 1 	(DW_OP_plus_uconst: 136)
<2><919>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x32): pid_ns
DW_AT_decl_file   : 19
DW_AT_decl_line   : 298
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 3 byte block: 23 90 1 	(DW_OP_plus_uconst: 144)
<2><92a>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xee7): mmap_cache
DW_AT_decl_file   : 19
DW_AT_decl_line   : 304
DW_AT_decl_column : 23
DW_AT_type        : <0xa0e>
DW_AT_data_member_location: 3 byte block: 23 94 1 	(DW_OP_plus_uconst: 148)
<2><93b>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa81): wait_data_idx
DW_AT_decl_file   : 19
DW_AT_decl_line   : 311
DW_AT_decl_column : 9
DW_AT_type        : <0x12e>
DW_AT_data_member_location: 3 byte block: 23 98 1 	(DW_OP_plus_uconst: 152)
<2><94c>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9c3): delayed_wait_data
DW_AT_decl_file   : 19
DW_AT_decl_line   : 313
DW_AT_decl_column : 24
DW_AT_type        : <0xa1a>
DW_AT_data_member_location: 3 byte block: 23 9c 1 	(DW_OP_plus_uconst: 156)
<2><95d>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa33): wait_list
DW_AT_decl_file   : 19
DW_AT_decl_line   : 314
DW_AT_decl_column : 19
DW_AT_type        : <0x5c3>
DW_AT_data_member_location: 3 byte block: 23 a0 1 	(DW_OP_plus_uconst: 160)
<2><96e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x611): vcpu_info_list
DW_AT_decl_file   : 19
DW_AT_decl_line   : 318
DW_AT_decl_column : 20
DW_AT_type        : <0xa26>
DW_AT_data_member_location: 3 byte block: 23 a8 1 	(DW_OP_plus_uconst: 168)
<2><97f>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc45): unwind_ctx
DW_AT_decl_file   : 19
DW_AT_decl_line   : 322
DW_AT_decl_column : 8
DW_AT_type        : <0xcd>
DW_AT_data_member_location: 3 byte block: 23 ac 1 	(DW_OP_plus_uconst: 172)
<2><990>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4a0): unwind_queue
DW_AT_decl_file   : 19
DW_AT_decl_line   : 323
DW_AT_decl_column : 25
DW_AT_type        : <0xa32>
DW_AT_data_member_location: 3 byte block: 23 b0 1 	(DW_OP_plus_uconst: 176)
<2><9a1>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x175): comm
DW_AT_decl_file   : 19
DW_AT_decl_line   : 327
DW_AT_decl_column : 7
DW_AT_type        : <0xa38>
DW_AT_data_member_location: 3 byte block: 23 b4 1 	(DW_OP_plus_uconst: 180)
<1><9b3>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x5b2>
DW_AT_sibling     : <0x9c3>
<2><9bc>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 5
<1><9c3>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x3bf>
<1><9c9>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xe90): staged_output_data
DW_AT_declaration : 1
<1><9cf>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x9c9>
<1><9d5>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x9e1>
<2><9db>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xcd>
<1><9e1>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x9d5>
<1><9e7>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x66b>
<1><9ed>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x9e7>
<1><9f2>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xa02>
DW_AT_sibling     : <0xa02>
<2><9fb>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 2
<1><a02>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x73f>
<1><a08>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xad): mmap_cache_t
DW_AT_declaration : 1
<1><a0e>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xa08>
<1><a14>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x3af): tcb_wait_data
DW_AT_declaration : 1
<1><a1a>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xa14>
<1><a20>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x16b): vcpu_info
DW_AT_declaration : 1
<1><a26>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xa20>
<1><a2c>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xe74): unwind_queue_t
DW_AT_declaration : 1
<1><a32>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xa2c>
<1><a38>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xe6>
DW_AT_sibling     : <0xa48>
<2><a41>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 15
<1><a48>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xabe): stub_sysent
DW_AT_decl_file   : 19
DW_AT_decl_line   : 400
DW_AT_decl_column : 28
DW_AT_type        : <0x66b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><a57>
Abbrev Number: 26 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x1007): xlat_type
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 20
DW_AT_decl_line   : 13
DW_AT_decl_column : 6
DW_AT_sibling     : <0xa7c>
<2><a69>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x2c4): XT_NORMAL
DW_AT_const_value : 0
<2><a6f>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xbe2): XT_SORTED
DW_AT_const_value : 1
<2><a75>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xd6d): XT_INDEXED
DW_AT_const_value : 2
<1><a7c>
Abbrev Number: 26 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0xaea): xlat_style
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 20
DW_AT_decl_line   : 19
DW_AT_decl_column : 6
DW_AT_sibling     : <0xab9>
<2><a8e>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xed): XLAT_STYLE_DEFAULT
DW_AT_const_value : 0
<2><a94>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xb1d): XLAT_STYLE_RAW
DW_AT_const_value : 1
<2><a9a>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xfd2): XLAT_STYLE_ABBREV
DW_AT_const_value : 2
<2><aa0>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x2e1): XLAT_STYLE_VERBOSE
DW_AT_const_value : 3
<2><aa6>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x11): XLAT_STYLE_FMT_X
DW_AT_const_value : 0
<2><aac>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x0): XLAT_STYLE_FMT_U
DW_AT_const_value : 4
<2><ab2>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x1041): XLAT_STYLE_FMT_D
DW_AT_const_value : 8
<1><ab9>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x325): xlat_data
DW_AT_byte_size   : 12
DW_AT_decl_file   : 20
DW_AT_decl_line   : 51
DW_AT_decl_column : 8
DW_AT_sibling     : <0xae5>
<2><ac6>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : val
DW_AT_decl_file   : 20
DW_AT_decl_line   : 52
DW_AT_decl_column : 11
DW_AT_type        : <0x116>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><ad5>
Abbrev Number: 19 (DW_TAG_member)
DW_AT_name        : str
DW_AT_decl_file   : 20
DW_AT_decl_line   : 53
DW_AT_decl_column : 14
DW_AT_type        : <0x1d5>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><ae5>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xab9>
<1><aea>
Abbrev Number: 8 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x22): xlat
DW_AT_byte_size   : 24
DW_AT_decl_file   : 20
DW_AT_decl_line   : 56
DW_AT_decl_column : 8
DW_AT_sibling     : <0xb43>
<2><af7>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1024): data
DW_AT_decl_file   : 20
DW_AT_decl_line   : 57
DW_AT_decl_column : 26
DW_AT_type        : <0xb48>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><b06>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x7b6): flags_strsz
DW_AT_decl_file   : 20
DW_AT_decl_line   : 58
DW_AT_decl_column : 9
DW_AT_type        : <0x12e>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><b15>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa8f): size
DW_AT_decl_file   : 20
DW_AT_decl_line   : 59
DW_AT_decl_column : 11
DW_AT_type        : <0x10a>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><b24>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x19c): type
DW_AT_decl_file   : 20
DW_AT_decl_line   : 60
DW_AT_decl_column : 17
DW_AT_type        : <0xa57>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><b33>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x66c): flags_mask
DW_AT_decl_file   : 20
DW_AT_decl_line   : 61
DW_AT_decl_column : 11
DW_AT_type        : <0x116>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<1><b43>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xaea>
<1><b48>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xae5>
<1><b4e>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0xb43>
DW_AT_sibling     : <0xb59>
<2><b57>
Abbrev Number: 18 (DW_TAG_subrange_type)
<1><b59>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xb4e>
<1><b5e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdd6): addrfams
DW_AT_decl_file   : 19
DW_AT_decl_line   : 406
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><b6d>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xcaf): arp_hardware_types
DW_AT_decl_file   : 19
DW_AT_decl_line   : 407
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><b7c>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf58): at_flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 408
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><b8b>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x47e): clocknames
DW_AT_decl_file   : 19
DW_AT_decl_line   : 409
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><b9a>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf23): dirent_types
DW_AT_decl_file   : 19
DW_AT_decl_line   : 410
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ba9>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x807): ethernet_protocols
DW_AT_decl_file   : 19
DW_AT_decl_line   : 411
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><bb8>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x592): inet_protocols
DW_AT_decl_file   : 19
DW_AT_decl_line   : 412
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><bc7>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x2b1): evdev_abs
DW_AT_decl_file   : 19
DW_AT_decl_line   : 413
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><bd6>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x661): audit_arch
DW_AT_decl_file   : 19
DW_AT_decl_line   : 414
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><be5>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x99): evdev_ev
DW_AT_decl_file   : 19
DW_AT_decl_line   : 415
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><bf4>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x45f): iffflags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 416
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c03>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xb2c): ip_type_of_services
DW_AT_decl_file   : 19
DW_AT_decl_line   : 417
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c12>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x5ed): ipc_private
DW_AT_decl_file   : 19
DW_AT_decl_line   : 418
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c21>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x31b): msg_flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 419
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c30>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x110): netlink_protocols
DW_AT_decl_file   : 19
DW_AT_decl_line   : 420
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c3f>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xea3): nl_bridge_vlan_flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 421
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c4e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd56): nl_netfilter_msg_types
DW_AT_decl_file   : 19
DW_AT_decl_line   : 422
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c5d>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x21d): nl_route_types
DW_AT_decl_file   : 19
DW_AT_decl_line   : 423
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c6c>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe1b): open_access_modes
DW_AT_decl_file   : 19
DW_AT_decl_line   : 424
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c7b>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x79): open_mode_flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 425
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c8a>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xbbe): perf_type_id
DW_AT_decl_file   : 19
DW_AT_decl_line   : 426
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><c99>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xddf): pollflags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 427
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ca8>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x533): ptrace_cmds
DW_AT_decl_file   : 19
DW_AT_decl_line   : 428
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><cb7>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x749): resource_flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 429
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><cc6>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x287): route_nexthop_flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 430
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><cd5>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe38): routing_protocols
DW_AT_decl_file   : 19
DW_AT_decl_line   : 431
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ce4>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x450): routing_scopes
DW_AT_decl_file   : 19
DW_AT_decl_line   : 432
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><cf3>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd44): routing_table_ids
DW_AT_decl_file   : 19
DW_AT_decl_line   : 433
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d02>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x5ca): routing_types
DW_AT_decl_file   : 19
DW_AT_decl_line   : 434
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d11>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x1c0): rwf_flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 435
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d20>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x781): seccomp_filter_flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 436
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d2f>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x2ce): seccomp_ret_action
DW_AT_decl_file   : 19
DW_AT_decl_line   : 437
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d3e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x419): setns_types
DW_AT_decl_file   : 19
DW_AT_decl_line   : 438
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d4d>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdcb): sg_io_info
DW_AT_decl_file   : 19
DW_AT_decl_line   : 439
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d5c>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xad2): socketlayers
DW_AT_decl_file   : 19
DW_AT_decl_line   : 440
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d6b>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd23): socktypes
DW_AT_decl_file   : 19
DW_AT_decl_line   : 441
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d7a>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x9ac): tcp_state_flags
DW_AT_decl_file   : 19
DW_AT_decl_line   : 442
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d89>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x696): tcp_states
DW_AT_decl_file   : 19
DW_AT_decl_line   : 443
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><d98>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xfb5): whence_codes
DW_AT_decl_file   : 19
DW_AT_decl_line   : 444
DW_AT_decl_column : 26
DW_AT_type        : <0xb59>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><da7>
Abbrev Number: 28 (DW_TAG_enumeration_type)
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 19
DW_AT_decl_line   : 505
DW_AT_decl_column : 14
DW_AT_sibling     : <0xdc9>
<2><db6>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x8d7): CFLAG_NONE
DW_AT_const_value : 0
<2><dbc>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x81a): CFLAG_ONLY_STATS
DW_AT_const_value : 1
<2><dc2>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xadf): CFLAG_BOTH
DW_AT_const_value : 2
<1><dc9>
Abbrev Number: 29 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1057): cflag_t
DW_AT_decl_file   : 19
DW_AT_decl_line   : 509
DW_AT_decl_column : 3
DW_AT_type        : <0xda7>
<1><dd6>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc6a): cflag
DW_AT_decl_file   : 19
DW_AT_decl_line   : 510
DW_AT_decl_column : 16
DW_AT_type        : <0xdc9>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><de5>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x18b): Tflag
DW_AT_decl_file   : 19
DW_AT_decl_line   : 511
DW_AT_decl_column : 13
DW_AT_type        : <0x582>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><df4>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x6fb): Tflag_scale
DW_AT_decl_file   : 19
DW_AT_decl_line   : 512
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><e03>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x796): Tflag_width
DW_AT_decl_file   : 19
DW_AT_decl_line   : 513
DW_AT_decl_column : 12
DW_AT_type        : <0x64>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><e12>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xdbd): iflag
DW_AT_decl_file   : 19
DW_AT_decl_line   : 514
DW_AT_decl_column : 13
DW_AT_type        : <0x582>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><e21>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x573): count_wallclock
DW_AT_decl_file   : 19
DW_AT_decl_line   : 515
DW_AT_decl_column : 13
DW_AT_type        : <0x582>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><e30>
Abbrev Number: 30 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x4a): path_set_item
DW_AT_byte_size   : 4
DW_AT_decl_file   : 19
DW_AT_decl_line   : 517
DW_AT_decl_column : 8
DW_AT_sibling     : <0xe4f>
<2><e3e>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc7): path
DW_AT_decl_file   : 19
DW_AT_decl_line   : 518
DW_AT_decl_column : 14
DW_AT_type        : <0x1d5>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<1><e4f>
Abbrev Number: 30 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x6a1): path_set
DW_AT_byte_size   : 12
DW_AT_decl_file   : 19
DW_AT_decl_line   : 522
DW_AT_decl_column : 15
DW_AT_sibling     : <0xe8e>
<2><e5d>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x628): paths_selected
DW_AT_decl_file   : 19
DW_AT_decl_line   : 523
DW_AT_decl_column : 24
DW_AT_type        : <0xe8e>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><e6d>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xfa8): num_selected
DW_AT_decl_file   : 19
DW_AT_decl_line   : 524
DW_AT_decl_column : 9
DW_AT_type        : <0x12e>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><e7d>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa8f): size
DW_AT_decl_file   : 19
DW_AT_decl_line   : 525
DW_AT_decl_column : 9
DW_AT_type        : <0x12e>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<1><e8e>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0xe30>
<1><e94>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xff7): global_path_set
DW_AT_decl_file   : 19
DW_AT_decl_line   : 526
DW_AT_decl_column : 3
DW_AT_type        : <0xe4f>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ea3>
Abbrev Number: 31 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0xf10): xflag_opts
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 19
DW_AT_decl_line   : 528
DW_AT_decl_column : 6
DW_AT_sibling     : <0xed5>
<2><eb6>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x96c): HEXSTR_NONE
DW_AT_const_value : 0
<2><ebc>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xf3a): HEXSTR_NON_ASCII
DW_AT_const_value : 1
<2><ec2>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x858): HEXSTR_ALL
DW_AT_const_value : 2
<2><ec8>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x5b3): HEXSTR_NON_ASCII_CHARS
DW_AT_const_value : 3
<2><ece>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xfc2): NUM_HEXSTR_OPTS
DW_AT_const_value : 4
<1><ed5>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd97): xflag
DW_AT_decl_file   : 19
DW_AT_decl_line   : 541
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ee4>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xd2d): followfork
DW_AT_decl_file   : 19
DW_AT_decl_line   : 542
DW_AT_decl_column : 13
DW_AT_type        : <0x582>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><ef3>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x32f): output_separately
DW_AT_decl_file   : 19
DW_AT_decl_line   : 543
DW_AT_decl_column : 13
DW_AT_type        : <0x582>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f02>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x22c): stack_trace_enabled
DW_AT_decl_file   : 19
DW_AT_decl_line   : 546
DW_AT_decl_column : 13
DW_AT_type        : <0x582>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f11>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x5a1): ptrace_setoptions
DW_AT_decl_file   : 19
DW_AT_decl_line   : 550
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f20>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x961): max_strlen
DW_AT_decl_file   : 19
DW_AT_decl_line   : 551
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f2f>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x98f): os_release
DW_AT_decl_file   : 19
DW_AT_decl_line   : 552
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f3e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x63e): xlat_verbosity
DW_AT_decl_file   : 19
DW_AT_decl_line   : 914
DW_AT_decl_column : 24
DW_AT_type        : <0xa7c>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><f4d>
Abbrev Number: 31 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0x556): xlat_style_private_flag_bits
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 19
DW_AT_decl_line   : 934
DW_AT_decl_column : 6
DW_AT_sibling     : <0xf79>
<2><f60>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x29b): PAF_PRINT_INDICES_BIT
DW_AT_const_value : 5
<2><f66>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xa46): PAF_ARRAY_TRUNCATED_BIT
DW_AT_const_value : 6
<2><f6c>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x3cb): PXF_DEFAULT_STR_BIT
DW_AT_const_value : 7
<2><f72>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0xbf5): SPFF_AUXSTR_MODE_BIT
DW_AT_const_value : 8
<1><f79>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x789>
<1><f7f>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xf79>
<1><f84>
Abbrev Number: 31 (DW_TAG_enumeration_type)
DW_AT_name        : (indirect string, offset: 0xcc2): find_xlat_flag_bits
DW_AT_encoding    : 7	(unsigned)
DW_AT_byte_size   : 4
DW_AT_type        : <0x2b>
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1438
DW_AT_decl_column : 6
DW_AT_sibling     : <0xf9e>
<2><f97>
Abbrev Number: 27 (DW_TAG_enumerator)
DW_AT_name        : (indirect string, offset: 0x895): FXL_CASE_SENSITIVE_BIT
DW_AT_const_value : 0
<1><f9e>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x93d): printing_tcp
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1684
DW_AT_decl_column : 20
DW_AT_type        : <0xf79>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fad>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x51e): errnoent
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1882
DW_AT_decl_column : 26
DW_AT_type        : <0x4b6>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fbc>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x7a2): signalent
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1883
DW_AT_decl_column : 26
DW_AT_type        : <0x4b6>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fcb>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe05): nerrnos
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1884
DW_AT_decl_column : 27
DW_AT_type        : <0x32>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fda>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xf91): nsignals
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1885
DW_AT_decl_column : 27
DW_AT_type        : <0x32>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><fe9>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x66b>
DW_AT_sibling     : <0xff4>
<2><ff2>
Abbrev Number: 18 (DW_TAG_subrange_type)
<1><ff4>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0xfe9>
<1><ff9>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc87): sysent0
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1887
DW_AT_decl_column : 28
DW_AT_type        : <0xff4>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1008>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x6d2>
DW_AT_sibling     : <0x1013>
<2><1011>
Abbrev Number: 18 (DW_TAG_subrange_type)
<1><1013>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1008>
<1><1018>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xfed): ioctlent0
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1888
DW_AT_decl_column : 30
DW_AT_type        : <0x1013>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1027>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x43e): personality_names
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1890
DW_AT_decl_column : 26
DW_AT_type        : <0x4b6>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1036>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x7c2): sysent
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1893
DW_AT_decl_column : 29
DW_AT_type        : <0x9e7>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1045>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xc0a): ioctlent
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1894
DW_AT_decl_column : 31
DW_AT_type        : <0x1054>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1054>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x6d2>
<1><105a>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x7ac): nsyscalls
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1900
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1069>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe2d): nioctlents
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1901
DW_AT_decl_column : 17
DW_AT_type        : <0x2b>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1078>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x32>
DW_AT_sibling     : <0x1088>
<2><1081>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 2
<1><1088>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1078>
<1><108d>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe83): nsyscall_vec
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1903
DW_AT_decl_column : 27
DW_AT_type        : <0x1088>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><109c>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x9ed>
DW_AT_sibling     : <0x10ac>
<2><10a5>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 2
<1><10ac>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x109c>
<1><10b1>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x6e8): sysent_vec
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1904
DW_AT_decl_column : 35
DW_AT_type        : <0x10ac>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><10c0>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x37a): inject_vec
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1905
DW_AT_decl_column : 28
DW_AT_type        : <0x9f2>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><10cf>
Abbrev Number: 30 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0xd16): audit_arch_t
DW_AT_byte_size   : 8
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1907
DW_AT_decl_column : 8
DW_AT_sibling     : <0x10fe>
<2><10dd>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x548): arch
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1908
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><10ed>
Abbrev Number: 13 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x923): flag
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1909
DW_AT_decl_column : 15
DW_AT_type        : <0x2b>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<1><10fe>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x10cf>
<1><1103>
Abbrev Number: 15 (DW_TAG_array_type)
DW_AT_type        : <0x10fe>
DW_AT_sibling     : <0x1113>
<2><110c>
Abbrev Number: 16 (DW_TAG_subrange_type)
DW_AT_type        : <0x2b>
DW_AT_upper_bound : 2
<1><1113>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1103>
<1><1118>
Abbrev Number: 10 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x886): audit_arch_vec
DW_AT_decl_file   : 19
DW_AT_decl_line   : 1912
DW_AT_decl_column : 34
DW_AT_type        : <0x1113>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1127>
Abbrev Number: 32 (DW_TAG_structure_type)
DW_AT_byte_size   : 180
DW_AT_decl_file   : 21
DW_AT_decl_line   : 2
DW_AT_decl_column : 9
DW_AT_sibling     : <0x13e1>
<2><1130>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1d8): block_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 3
DW_AT_decl_column : 8
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 2 byte block: 23 0 	(DW_OP_plus_uconst: 0)
<2><113f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x9e5): btrfs_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 6
DW_AT_decl_column : 8
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 2 byte block: 23 4 	(DW_OP_plus_uconst: 4)
<2><114e>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x677): evdev_write_ioctl_mpers
DW_AT_decl_file   : 21
DW_AT_decl_line   : 9
DW_AT_decl_column : 8
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 2 byte block: 23 8 	(DW_OP_plus_uconst: 8)
<2><115d>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x64d): get_sock_fprog_size
DW_AT_decl_file   : 21
DW_AT_decl_line   : 12
DW_AT_decl_column : 17
DW_AT_type        : <0x1407>
DW_AT_data_member_location: 2 byte block: 23 c 	(DW_OP_plus_uconst: 12)
<2><116c>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x1a7): fetch_bpf_fprog
DW_AT_decl_file   : 21
DW_AT_decl_line   : 15
DW_AT_decl_column : 10
DW_AT_type        : <0x1427>
DW_AT_data_member_location: 2 byte block: 23 10 	(DW_OP_plus_uconst: 16)
<2><117b>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x873): fetch_struct_flock
DW_AT_decl_file   : 21
DW_AT_decl_line   : 18
DW_AT_decl_column : 10
DW_AT_type        : <0x1427>
DW_AT_data_member_location: 2 byte block: 23 14 	(DW_OP_plus_uconst: 20)
<2><118a>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xc30): fetch_struct_flock64
DW_AT_decl_file   : 21
DW_AT_decl_line   : 21
DW_AT_decl_column : 10
DW_AT_type        : <0x1427>
DW_AT_data_member_location: 2 byte block: 23 18 	(DW_OP_plus_uconst: 24)
<2><1199>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x158): fetch_struct_iovec
DW_AT_decl_file   : 21
DW_AT_decl_line   : 24
DW_AT_decl_column : 10
DW_AT_type        : <0x1427>
DW_AT_data_member_location: 2 byte block: 23 1c 	(DW_OP_plus_uconst: 28)
<2><11a8>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x61): fetch_keyctl_kdf_params
DW_AT_decl_file   : 21
DW_AT_decl_line   : 27
DW_AT_decl_column : 8
DW_AT_type        : <0x1453>
DW_AT_data_member_location: 2 byte block: 23 20 	(DW_OP_plus_uconst: 32)
<2><11b7>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x5d8): fetch_struct_mmsghdr
DW_AT_decl_file   : 21
DW_AT_decl_line   : 30
DW_AT_decl_column : 8
DW_AT_type        : <0x1473>
DW_AT_data_member_location: 2 byte block: 23 24 	(DW_OP_plus_uconst: 36)
<2><11c6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd00): sizeof_struct_mmsghdr
DW_AT_decl_file   : 21
DW_AT_decl_line   : 33
DW_AT_decl_column : 17
DW_AT_type        : <0x1407>
DW_AT_data_member_location: 2 byte block: 23 28 	(DW_OP_plus_uconst: 40)
<2><11d5>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa5e): fetch_struct_msghdr
DW_AT_decl_file   : 21
DW_AT_decl_line   : 36
DW_AT_decl_column : 8
DW_AT_type        : <0x1473>
DW_AT_data_member_location: 2 byte block: 23 2c 	(DW_OP_plus_uconst: 44)
<2><11e4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x6aa): fetch_struct_stat
DW_AT_decl_file   : 21
DW_AT_decl_line   : 39
DW_AT_decl_column : 10
DW_AT_type        : <0x14a4>
DW_AT_data_member_location: 2 byte block: 23 30 	(DW_OP_plus_uconst: 48)
<2><11f3>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa0b): fetch_struct_stat64
DW_AT_decl_file   : 21
DW_AT_decl_line   : 42
DW_AT_decl_column : 10
DW_AT_type        : <0x14a4>
DW_AT_data_member_location: 2 byte block: 23 34 	(DW_OP_plus_uconst: 52)
<2><1202>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x425): fetch_struct_statfs
DW_AT_decl_file   : 21
DW_AT_decl_line   : 45
DW_AT_decl_column : 10
DW_AT_type        : <0x14d5>
DW_AT_data_member_location: 2 byte block: 23 38 	(DW_OP_plus_uconst: 56)
<2><1211>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x7d4): fetch_struct_statfs64
DW_AT_decl_file   : 21
DW_AT_decl_line   : 48
DW_AT_decl_column : 10
DW_AT_type        : <0x14fa>
DW_AT_data_member_location: 2 byte block: 23 3c 	(DW_OP_plus_uconst: 60)
<2><1220>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x122): fetch_struct_quotastat
DW_AT_decl_file   : 21
DW_AT_decl_line   : 51
DW_AT_decl_column : 10
DW_AT_type        : <0x151a>
DW_AT_data_member_location: 2 byte block: 23 40 	(DW_OP_plus_uconst: 64)
<2><122f>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa2): hdio_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 54
DW_AT_decl_column : 8
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 2 byte block: 23 44 	(DW_OP_plus_uconst: 68)
<2><123e>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xa24): kd_mpers_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 57
DW_AT_decl_column : 8
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 2 byte block: 23 48 	(DW_OP_plus_uconst: 72)
<2><124d>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x984): loop_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 60
DW_AT_decl_column : 8
DW_AT_type        : <0x153a>
DW_AT_data_member_location: 2 byte block: 23 4c 	(DW_OP_plus_uconst: 76)
<2><125c>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x863): mtd_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 63
DW_AT_decl_column : 8
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 2 byte block: 23 50 	(DW_OP_plus_uconst: 80)
<2><126b>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xca4): perf_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 66
DW_AT_decl_column : 8
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 2 byte block: 23 54 	(DW_OP_plus_uconst: 84)
<2><127a>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x739): print_group_req
DW_AT_decl_file   : 21
DW_AT_decl_line   : 69
DW_AT_decl_column : 9
DW_AT_type        : <0x1556>
DW_AT_data_member_location: 2 byte block: 23 58 	(DW_OP_plus_uconst: 88)
<2><1289>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x3f7): print_kernel_sigset
DW_AT_decl_file   : 21
DW_AT_decl_line   : 72
DW_AT_decl_column : 9
DW_AT_type        : <0x156d>
DW_AT_data_member_location: 2 byte block: 23 5c 	(DW_OP_plus_uconst: 92)
<2><1298>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xdb1): printmqattr
DW_AT_decl_file   : 21
DW_AT_decl_line   : 75
DW_AT_decl_column : 9
DW_AT_type        : <0x1589>
DW_AT_data_member_location: 2 byte block: 23 60 	(DW_OP_plus_uconst: 96)
<2><12a7>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xe66): tprint_msgbuf
DW_AT_decl_file   : 21
DW_AT_decl_line   : 78
DW_AT_decl_column : 9
DW_AT_type        : <0x15a5>
DW_AT_data_member_location: 2 byte block: 23 64 	(DW_OP_plus_uconst: 100)
<2><12b6>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x8e7): decode_sg_req_info
DW_AT_decl_file   : 21
DW_AT_decl_line   : 81
DW_AT_decl_column : 8
DW_AT_type        : <0x15c0>
DW_AT_data_member_location: 2 byte block: 23 68 	(DW_OP_plus_uconst: 104)
<2><12c5>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x583): print_sigevent
DW_AT_decl_file   : 21
DW_AT_decl_line   : 84
DW_AT_decl_column : 9
DW_AT_type        : <0x15d7>
DW_AT_data_member_location: 2 byte block: 23 6c 	(DW_OP_plus_uconst: 108)
<2><12d4>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xcc): print_struct_timeval
DW_AT_decl_file   : 21
DW_AT_decl_line   : 87
DW_AT_decl_column : 9
DW_AT_type        : <0x15e9>
DW_AT_data_member_location: 2 byte block: 23 70 	(DW_OP_plus_uconst: 112)
<2><12e3>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4e3): print_struct_timeval_data_size
DW_AT_decl_file   : 21
DW_AT_decl_line   : 90
DW_AT_decl_column : 10
DW_AT_type        : <0x1604>
DW_AT_data_member_location: 2 byte block: 23 74 	(DW_OP_plus_uconst: 116)
<2><12f2>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xd78): print_timeval
DW_AT_decl_file   : 21
DW_AT_decl_line   : 93
DW_AT_decl_column : 8
DW_AT_type        : <0x15c0>
DW_AT_data_member_location: 2 byte block: 23 78 	(DW_OP_plus_uconst: 120)
<2><1301>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xef2): print_timeval_utimes
DW_AT_decl_file   : 21
DW_AT_decl_line   : 96
DW_AT_decl_column : 8
DW_AT_type        : <0x15c0>
DW_AT_data_member_location: 2 byte block: 23 7c 	(DW_OP_plus_uconst: 124)
<2><1310>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xecc): sprint_timeval
DW_AT_decl_file   : 21
DW_AT_decl_line   : 99
DW_AT_decl_column : 17
DW_AT_type        : <0x161f>
DW_AT_data_member_location: 3 byte block: 23 80 1 	(DW_OP_plus_uconst: 128)
<2><1320>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x94a): print_itimerval
DW_AT_decl_file   : 21
DW_AT_decl_line   : 102
DW_AT_decl_column : 8
DW_AT_type        : <0x15c0>
DW_AT_data_member_location: 3 byte block: 23 84 1 	(DW_OP_plus_uconst: 132)
<2><1330>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x715): printrusage
DW_AT_decl_file   : 21
DW_AT_decl_line   : 105
DW_AT_decl_column : 9
DW_AT_type        : <0x15d7>
DW_AT_data_member_location: 3 byte block: 23 88 1 	(DW_OP_plus_uconst: 136)
<2><1340>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x148): printsiginfo_at
DW_AT_decl_file   : 21
DW_AT_decl_line   : 108
DW_AT_decl_column : 9
DW_AT_type        : <0x15d7>
DW_AT_data_member_location: 3 byte block: 23 8c 1 	(DW_OP_plus_uconst: 140)
<2><1350>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x4cf): print_siginfo_array
DW_AT_decl_file   : 21
DW_AT_decl_line   : 111
DW_AT_decl_column : 9
DW_AT_type        : <0x15a5>
DW_AT_data_member_location: 3 byte block: 23 90 1 	(DW_OP_plus_uconst: 144)
<2><1360>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x489): decode_prstatus_regset
DW_AT_decl_file   : 21
DW_AT_decl_line   : 114
DW_AT_decl_column : 9
DW_AT_type        : <0x15a5>
DW_AT_data_member_location: 3 byte block: 23 94 1 	(DW_OP_plus_uconst: 148)
<2><1370>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x82b): decode_fpregset
DW_AT_decl_file   : 21
DW_AT_decl_line   : 117
DW_AT_decl_column : 9
DW_AT_type        : <0x15a5>
DW_AT_data_member_location: 3 byte block: 23 98 1 	(DW_OP_plus_uconst: 152)
<2><1380>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x849): decode_pt_regs
DW_AT_decl_file   : 21
DW_AT_decl_line   : 120
DW_AT_decl_column : 9
DW_AT_type        : <0x15d7>
DW_AT_data_member_location: 3 byte block: 23 9c 1 	(DW_OP_plus_uconst: 156)
<2><1390>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x341): decode_pt_fpregs
DW_AT_decl_file   : 21
DW_AT_decl_line   : 123
DW_AT_decl_column : 9
DW_AT_type        : <0x15d7>
DW_AT_data_member_location: 3 byte block: 23 a0 1 	(DW_OP_plus_uconst: 160)
<2><13a0>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x933): rtc_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 126
DW_AT_decl_column : 8
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 3 byte block: 23 a4 1 	(DW_OP_plus_uconst: 164)
<2><13b0>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xf7b): decode_sg_io_v3
DW_AT_decl_file   : 21
DW_AT_decl_line   : 129
DW_AT_decl_column : 8
DW_AT_type        : <0x15c0>
DW_AT_data_member_location: 3 byte block: 23 a8 1 	(DW_OP_plus_uconst: 168)
<2><13c0>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0xda6): sock_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 132
DW_AT_decl_column : 8
DW_AT_type        : <0x153a>
DW_AT_data_member_location: 3 byte block: 23 ac 1 	(DW_OP_plus_uconst: 172)
<2><13d0>
Abbrev Number: 9 (DW_TAG_member)
DW_AT_name        : (indirect string, offset: 0x27c): v4l2_ioctl
DW_AT_decl_file   : 21
DW_AT_decl_line   : 135
DW_AT_decl_column : 8
DW_AT_type        : <0x13fb>
DW_AT_data_member_location: 3 byte block: 23 b0 1 	(DW_OP_plus_uconst: 176)
<1><13e1>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x13fb>
<2><13eb>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><13f0>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x32>
<2><13f5>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<1><13fb>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x13e1>
<1><1401>
Abbrev Number: 34 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x2b>
<1><1407>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1401>
<1><140d>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x582>
DW_AT_sibling     : <0x1427>
<2><1417>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><141c>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><1421>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xcf>
<1><1427>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x140d>
<1><142d>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x1447>
<2><1437>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><143c>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5b2>
<2><1441>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x1447>
<1><1447>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x144d>
<1><144d>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1f4): strace_keyctl_kdf_params
DW_AT_declaration : 1
<1><1453>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x142d>
<1><1459>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x1473>
<2><1463>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><1468>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><146d>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xcf>
<1><1473>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1459>
<1><1479>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x582>
DW_AT_sibling     : <0x1493>
<2><1483>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><1488>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><148d>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x1499>
<1><1493>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x149e>
<1><1499>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1493>
<1><149e>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1035): strace_stat
DW_AT_declaration : 1
<1><14a4>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1479>
<1><14aa>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x582>
DW_AT_sibling     : <0x14c4>
<2><14b4>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><14b9>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><14be>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x14ca>
<1><14c4>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x14cf>
<1><14ca>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x14c4>
<1><14cf>
Abbrev Number: 17 (DW_TAG_structure_type)
DW_AT_name        : (indirect string, offset: 0x1011): strace_statfs
DW_AT_declaration : 1
<1><14d5>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x14aa>
<1><14db>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x582>
DW_AT_sibling     : <0x14fa>
<2><14e5>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><14ea>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><14ef>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><14f4>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x14ca>
<1><14fa>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x14db>
<1><1500>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x582>
DW_AT_sibling     : <0x151a>
<2><150a>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><150f>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><1514>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xcd>
<1><151a>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1500>
<1><1520>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x153a>
<2><152a>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf79>
<2><152f>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x32>
<2><1534>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<1><153a>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1520>
<1><1540>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x1556>
<2><1546>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><154b>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><1550>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x6b>
<1><1556>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1540>
<1><155c>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x156d>
<2><1562>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf79>
<2><1567>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<1><156d>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x155c>
<1><1573>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x1589>
<2><1579>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><157e>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><1583>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x589>
<1><1589>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1573>
<1><158f>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x15a5>
<2><1595>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><159a>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<2><159f>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<1><15a5>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x158f>
<1><15ab>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x64>
DW_AT_sibling     : <0x15c0>
<2><15b5>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><15ba>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<1><15c0>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x15ab>
<1><15c6>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x15d7>
<2><15cc>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><15d1>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<1><15d7>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x15c6>
<1><15dd>
Abbrev Number: 24 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_sibling     : <0x15e9>
<2><15e3>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x1e0>
<1><15e9>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x15dd>
<1><15ef>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x582>
DW_AT_sibling     : <0x1604>
<2><15f9>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x1e0>
<2><15fe>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x13a>
<1><1604>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x15ef>
<1><160a>
Abbrev Number: 33 (DW_TAG_subroutine_type)
DW_AT_prototyped  : 1
DW_AT_type        : <0x1d5>
DW_AT_sibling     : <0x161f>
<2><1614>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0xf7f>
<2><1619>
Abbrev Number: 25 (DW_TAG_formal_parameter)
DW_AT_type        : <0x5be>
<1><161f>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x160a>
<1><1625>
Abbrev Number: 4 (DW_TAG_typedef)
DW_AT_name        : (indirect string, offset: 0x1e4): struct_printers
DW_AT_decl_file   : 21
DW_AT_decl_line   : 138
DW_AT_decl_column : 3
DW_AT_type        : <0x1127>
<1><1631>
Abbrev Number: 3 (DW_TAG_const_type)
DW_AT_type        : <0x1625>
<1><1636>
Abbrev Number: 11 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0x214): printers
DW_AT_decl_file   : 21
DW_AT_decl_line   : 139
DW_AT_decl_column : 31
DW_AT_type        : <0x1644>
DW_AT_external    : 1
DW_AT_declaration : 1
<1><1644>
Abbrev Number: 7 (DW_TAG_pointer_type)
DW_AT_byte_size   : 4
DW_AT_type        : <0x1631>
<1><164a>
Abbrev Number: 35 (DW_TAG_variable)
DW_AT_name        : (indirect string, offset: 0xe4a): mpers_target_var
DW_AT_decl_file   : 22
DW_AT_decl_line   : 12
DW_AT_decl_column : 8
DW_AT_type        : <0x122>
DW_AT_external    : 1
DW_AT_location    : 5 byte block: 3 4 0 0 0 	(DW_OP_addr: 4)
